-- Bootstrap 002: archived baseline migrations
-- Generated by scripts/build-bootstrap-sql.mjs — do not edit by hand

-- ============================================================
-- sql/保留存档sql/sql1.0.0/001_daily_records_and_items.sql
-- ============================================================

-- 创建 daily_records 表
CREATE TABLE IF NOT EXISTS public.daily_records (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID NOT NULL,
  record_date DATE NOT NULL,
  note TEXT,
  total_score INTEGER,
  completion_rate INTEGER,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, NOW()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, NOW()) NOT NULL
);

-- 创建 daily_record_items 表
CREATE TABLE IF NOT EXISTS public.daily_record_items (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  daily_record_id UUID NOT NULL REFERENCES public.daily_records(id) ON DELETE CASCADE,
  item_key TEXT NOT NULL,
  item_name TEXT NOT NULL,
  value_number INTEGER,
  value_duration INTEGER,
  value_time TEXT,
  value_text TEXT,
  unit TEXT,
  sort_order INTEGER,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, NOW()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, NOW()) NOT NULL
);

-- 创建唯一索引（确保每个用户每天只有一条记录）
CREATE UNIQUE INDEX IF NOT EXISTS daily_records_user_date_idx 
  ON public.daily_records(user_id, record_date);

-- 为 daily_record_items 创建索引
CREATE INDEX IF NOT EXISTS daily_record_items_daily_record_id_idx 
  ON public.daily_record_items(daily_record_id);

CREATE INDEX IF NOT EXISTS daily_record_items_item_key_idx 
  ON public.daily_record_items(item_key);

-- 添加注释
COMMENT ON TABLE public.daily_records IS '每日记录表';
COMMENT ON TABLE public.daily_record_items IS '每日记录项表';

COMMENT ON COLUMN public.daily_records.user_id IS '用户ID';
COMMENT ON COLUMN public.daily_records.record_date IS '记录日期';
COMMENT ON COLUMN public.daily_records.note IS '备注';
COMMENT ON COLUMN public.daily_records.total_score IS '总分';
COMMENT ON COLUMN public.daily_records.completion_rate IS '完成率';

COMMENT ON COLUMN public.daily_record_items.daily_record_id IS '关联的每日记录ID';
COMMENT ON COLUMN public.daily_record_items.item_key IS '项目键值';
COMMENT ON COLUMN public.daily_record_items.item_name IS '项目名称';
COMMENT ON COLUMN public.daily_record_items.value_number IS '数值';
COMMENT ON COLUMN public.daily_record_items.value_duration IS '时长（分钟）';
COMMENT ON COLUMN public.daily_record_items.value_time IS '时间';
COMMENT ON COLUMN public.daily_record_items.value_text IS '文本值';
COMMENT ON COLUMN public.daily_record_items.unit IS '单位';
COMMENT ON COLUMN public.daily_record_items.sort_order IS '排序';

-- ============================================================
-- sql/保留存档sql/sql1.0.0/003_diary_reviews.sql
-- ============================================================

-- 创建 diary_reviews 表
CREATE TABLE IF NOT EXISTS public.diary_reviews (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID NOT NULL,
  review_date DATE NOT NULL,
  did_what TEXT,
  planned_what TEXT,
  completion_rate INTEGER,
  status_label TEXT,
  emotion_label TEXT,
  biggest_progress TEXT,
  biggest_problem TEXT,
  tomorrow_plan TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, NOW()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, NOW()) NOT NULL
);

-- 创建唯一索引（确保每个用户每天只有一条记录）
CREATE UNIQUE INDEX IF NOT EXISTS diary_reviews_user_date_idx 
  ON public.diary_reviews(user_id, review_date);

-- 添加注释
COMMENT ON TABLE public.diary_reviews IS '日记复盘表';

COMMENT ON COLUMN public.diary_reviews.user_id IS '用户ID';
COMMENT ON COLUMN public.diary_reviews.review_date IS '复盘日期';
COMMENT ON COLUMN public.diary_reviews.did_what IS '今天做了什么';
COMMENT ON COLUMN public.diary_reviews.planned_what IS '原本计划做什么';
COMMENT ON COLUMN public.diary_reviews.completion_rate IS '完成度（0-100）';
COMMENT ON COLUMN public.diary_reviews.status_label IS '今日状态';
COMMENT ON COLUMN public.diary_reviews.emotion_label IS '今日情绪';
COMMENT ON COLUMN public.diary_reviews.biggest_progress IS '今天最重要的推进';
COMMENT ON COLUMN public.diary_reviews.biggest_problem IS '今天最大的问题';
COMMENT ON COLUMN public.diary_reviews.tomorrow_plan IS '明日计划';

-- ============================================================
-- sql/保留存档sql/sql1.0.0/004_projects_and_logs.sql
-- ============================================================

  -- 创建 projects 表
  CREATE TABLE IF NOT EXISTS public.projects (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID NOT NULL,
    name TEXT NOT NULL,
    category TEXT NOT NULL,
    description TEXT,
    unit TEXT NOT NULL,
    target_total INTEGER NOT NULL,
    current_progress INTEGER NOT NULL DEFAULT 0,
    start_date DATE NOT NULL,
    target_date DATE NOT NULL,
    status TEXT NOT NULL DEFAULT 'active',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, NOW()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, NOW()) NOT NULL
  );

  -- 创建 project_logs 表
  CREATE TABLE IF NOT EXISTS public.project_logs (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    project_id UUID NOT NULL REFERENCES public.projects(id) ON DELETE CASCADE,
    log_date DATE NOT NULL,
    progress_added INTEGER NOT NULL,
    progress_before INTEGER NOT NULL,
    progress_after INTEGER NOT NULL,
    note TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, NOW()) NOT NULL
  );

  -- 为 projects 创建索引
  CREATE INDEX IF NOT EXISTS projects_user_id_idx 
    ON public.projects(user_id);

  CREATE INDEX IF NOT EXISTS projects_status_idx 
    ON public.projects(status);

  -- 为 project_logs 创建索引
  CREATE INDEX IF NOT EXISTS project_logs_project_id_idx 
    ON public.project_logs(project_id);

  CREATE INDEX IF NOT EXISTS project_logs_log_date_idx 
    ON public.project_logs(log_date);

  -- 添加注释
  COMMENT ON TABLE public.projects IS '项目表';
  COMMENT ON TABLE public.project_logs IS '项目日志表';

  COMMENT ON COLUMN public.projects.user_id IS '用户ID';
  COMMENT ON COLUMN public.projects.name IS '项目名称';
  COMMENT ON COLUMN public.projects.category IS '项目分类';
  COMMENT ON COLUMN public.projects.description IS '项目描述';
  COMMENT ON COLUMN public.projects.unit IS '单位';
  COMMENT ON COLUMN public.projects.target_total IS '目标总量';
  COMMENT ON COLUMN public.projects.current_progress IS '当前进度';
  COMMENT ON COLUMN public.projects.start_date IS '开始日期';
  COMMENT ON COLUMN public.projects.target_date IS '目标日期';
  COMMENT ON COLUMN public.projects.status IS '状态（active/paused/completed）';

  COMMENT ON COLUMN public.project_logs.project_id IS '关联项目ID';
  COMMENT ON COLUMN public.project_logs.log_date IS '日志日期';
  COMMENT ON COLUMN public.project_logs.progress_added IS '本次新增进度';
  COMMENT ON COLUMN public.project_logs.progress_before IS '更新前进度';
  COMMENT ON COLUMN public.project_logs.progress_after IS '更新后进度';
  COMMENT ON COLUMN public.project_logs.note IS '备注';

-- ============================================================
-- sql/保留存档sql/sql1.0.1/001_init_core_tables.sql
-- ============================================================

-- TETO 1.0 核心数据库表初始化
-- 文件: sql/001_init_core_tables.sql
-- 说明: 创建 6 张核心表，包含完整的约束和索引
-- 执行方式: 在 Supabase SQL Editor 中执行

-- ============================================
-- 1. profiles 表 (用户扩展信息)
-- ============================================
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  email TEXT,
  display_name TEXT,
  avatar_url TEXT,
  timezone TEXT DEFAULT 'Asia/Shanghai',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, NOW()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, NOW()) NOT NULL
);

-- profiles 表索引
CREATE INDEX IF NOT EXISTS profiles_email_idx ON public.profiles(email);

-- profiles 表注释
COMMENT ON TABLE public.profiles IS '用户扩展信息表';
COMMENT ON COLUMN public.profiles.id IS '用户ID，关联 auth.users';
COMMENT ON COLUMN public.profiles.email IS '用户邮箱';
COMMENT ON COLUMN public.profiles.display_name IS '显示名称';
COMMENT ON COLUMN public.profiles.avatar_url IS '头像URL';
COMMENT ON COLUMN public.profiles.timezone IS '时区';

-- ============================================
-- 2. daily_records 表 (每日记录)
-- ============================================
CREATE TABLE IF NOT EXISTS public.daily_records (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  record_date DATE NOT NULL,
  note TEXT,
  total_score INTEGER,
  completion_rate INTEGER,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, NOW()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, NOW()) NOT NULL
);

-- daily_records 唯一约束：每个用户每天只有一条记录
CREATE UNIQUE INDEX IF NOT EXISTS daily_records_user_date_idx 
  ON public.daily_records(user_id, record_date);

-- daily_records 表注释
COMMENT ON TABLE public.daily_records IS '每日记录表';
COMMENT ON COLUMN public.daily_records.user_id IS '用户ID';
COMMENT ON COLUMN public.daily_records.record_date IS '记录日期';
COMMENT ON COLUMN public.daily_records.note IS '备注';
COMMENT ON COLUMN public.daily_records.total_score IS '总分';
COMMENT ON COLUMN public.daily_records.completion_rate IS '完成率';

-- ============================================
-- 3. daily_record_items 表 (每日记录项)
-- ============================================
CREATE TABLE IF NOT EXISTS public.daily_record_items (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  daily_record_id UUID NOT NULL REFERENCES public.daily_records(id) ON DELETE CASCADE,
  item_key TEXT NOT NULL,
  item_name TEXT NOT NULL,
  value_number INTEGER,
  value_duration INTEGER,
  value_time TIME,
  value_text TEXT,
  unit TEXT,
  sort_order INTEGER,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, NOW()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, NOW()) NOT NULL
);

-- daily_record_items 唯一约束：每条记录中每个 item_key 只能出现一次
CREATE UNIQUE INDEX IF NOT EXISTS daily_record_items_record_key_idx 
  ON public.daily_record_items(daily_record_id, item_key);

-- daily_record_items 索引
CREATE INDEX IF NOT EXISTS daily_record_items_daily_record_id_idx 
  ON public.daily_record_items(daily_record_id);
CREATE INDEX IF NOT EXISTS daily_record_items_item_key_idx 
  ON public.daily_record_items(item_key);

-- daily_record_items 表注释
COMMENT ON TABLE public.daily_record_items IS '每日记录项表';
COMMENT ON COLUMN public.daily_record_items.daily_record_id IS '关联的每日记录ID';
COMMENT ON COLUMN public.daily_record_items.item_key IS '项目键名';
COMMENT ON COLUMN public.daily_record_items.item_name IS '项目名称';
COMMENT ON COLUMN public.daily_record_items.value_number IS '数值';
COMMENT ON COLUMN public.daily_record_items.value_duration IS '时长（分钟）';
COMMENT ON COLUMN public.daily_record_items.value_time IS '时间点';
COMMENT ON COLUMN public.daily_record_items.value_text IS '文本值';
COMMENT ON COLUMN public.daily_record_items.unit IS '单位';
COMMENT ON COLUMN public.daily_record_items.sort_order IS '排序顺序';

-- ============================================
-- 4. diary_reviews 表 (日记复盘)
-- ============================================
CREATE TABLE IF NOT EXISTS public.diary_reviews (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  review_date DATE NOT NULL,
  did_what TEXT,
  planned_what TEXT,
  completion_rate INTEGER,
  status_label TEXT,
  emotion_label TEXT,
  biggest_progress TEXT,
  biggest_problem TEXT,
  tomorrow_plan TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, NOW()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, NOW()) NOT NULL
);

-- diary_reviews 唯一约束：每个用户每天只有一条复盘记录
CREATE UNIQUE INDEX IF NOT EXISTS diary_reviews_user_date_idx 
  ON public.diary_reviews(user_id, review_date);

-- diary_reviews 表注释
COMMENT ON TABLE public.diary_reviews IS '日记复盘表';
COMMENT ON COLUMN public.diary_reviews.user_id IS '用户ID';
COMMENT ON COLUMN public.diary_reviews.review_date IS '复盘日期';
COMMENT ON COLUMN public.diary_reviews.did_what IS '今天做了什么';
COMMENT ON COLUMN public.diary_reviews.planned_what IS '原本计划做什么';
COMMENT ON COLUMN public.diary_reviews.completion_rate IS '完成度（0-100）';
COMMENT ON COLUMN public.diary_reviews.status_label IS '今日状态';
COMMENT ON COLUMN public.diary_reviews.emotion_label IS '今日情绪';
COMMENT ON COLUMN public.diary_reviews.biggest_progress IS '今天最重要的推进';
COMMENT ON COLUMN public.diary_reviews.biggest_problem IS '今天最大的问题';
COMMENT ON COLUMN public.diary_reviews.tomorrow_plan IS '明日计划';

-- ============================================
-- 5. projects 表 (项目)
-- ============================================
CREATE TABLE IF NOT EXISTS public.projects (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  category TEXT NOT NULL,
  description TEXT,
  unit TEXT NOT NULL,
  target_total INTEGER NOT NULL,
  current_progress INTEGER NOT NULL DEFAULT 0,
  start_date DATE NOT NULL,
  target_date DATE NOT NULL,
  status TEXT NOT NULL DEFAULT 'active',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, NOW()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, NOW()) NOT NULL
);

-- projects 索引
CREATE INDEX IF NOT EXISTS projects_user_id_idx ON public.projects(user_id);
CREATE INDEX IF NOT EXISTS projects_status_idx ON public.projects(status);

-- projects 表注释
COMMENT ON TABLE public.projects IS '项目表';
COMMENT ON COLUMN public.projects.user_id IS '用户ID';
COMMENT ON COLUMN public.projects.name IS '项目名称';
COMMENT ON COLUMN public.projects.category IS '项目分类';
COMMENT ON COLUMN public.projects.description IS '项目描述';
COMMENT ON COLUMN public.projects.unit IS '单位';
COMMENT ON COLUMN public.projects.target_total IS '目标总量';
COMMENT ON COLUMN public.projects.current_progress IS '当前进度';
COMMENT ON COLUMN public.projects.start_date IS '开始日期';
COMMENT ON COLUMN public.projects.target_date IS '目标日期';
COMMENT ON COLUMN public.projects.status IS '状态（active/paused/completed）';

-- ============================================
-- 6. project_logs 表 (项目日志)
-- ============================================
CREATE TABLE IF NOT EXISTS public.project_logs (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  project_id UUID NOT NULL REFERENCES public.projects(id) ON DELETE CASCADE,
  log_date DATE NOT NULL,
  progress_added INTEGER NOT NULL,
  progress_before INTEGER NOT NULL,
  progress_after INTEGER NOT NULL,
  note TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, NOW()) NOT NULL
);

-- project_logs 索引
CREATE INDEX IF NOT EXISTS project_logs_project_id_idx ON public.project_logs(project_id);
CREATE INDEX IF NOT EXISTS project_logs_log_date_idx ON public.project_logs(log_date);

-- ============================================================
-- sql/保留存档sql/sql1.0.1/002_enable_rls_core_tables.sql
-- ============================================================

-- TETO 1.0 核心表 RLS 安全策略配置
-- 文件: sql/002_enable_rls_core_tables.sql
-- 说明: 为 6 张核心表启用行级安全策略，确保用户只能访问自己的数据
-- 执行方式: 在 Supabase SQL Editor 中执行

-- ============================================
-- 1. profiles 表 RLS 策略
-- ============================================

-- 启用 RLS
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- 删除已存在的策略（避免重复错误）
DROP POLICY IF EXISTS "Users can view own profile" ON public.profiles;
DROP POLICY IF EXISTS "Users can insert own profile" ON public.profiles;
DROP POLICY IF EXISTS "Users can update own profile" ON public.profiles;
DROP POLICY IF EXISTS "Users can delete own profile" ON public.profiles;

-- SELECT 策略：只能查看自己的 profile
CREATE POLICY "Users can view own profile"
  ON public.profiles
  FOR SELECT
  USING (id = auth.uid());

-- INSERT 策略：只能插入自己的 profile
CREATE POLICY "Users can insert own profile"
  ON public.profiles
  FOR INSERT
  WITH CHECK (id = auth.uid());

-- UPDATE 策略：只能更新自己的 profile
CREATE POLICY "Users can update own profile"
  ON public.profiles
  FOR UPDATE
  USING (id = auth.uid())
  WITH CHECK (id = auth.uid());

-- DELETE 策略：只能删除自己的 profile
CREATE POLICY "Users can delete own profile"
  ON public.profiles
  FOR DELETE
  USING (id = auth.uid());

-- ============================================
-- 2. daily_records 表 RLS 策略
-- ============================================

-- 启用 RLS
ALTER TABLE public.daily_records ENABLE ROW LEVEL SECURITY;

-- 删除已存在的策略
DROP POLICY IF EXISTS "Users can view own daily records" ON public.daily_records;
DROP POLICY IF EXISTS "Users can insert own daily records" ON public.daily_records;
DROP POLICY IF EXISTS "Users can update own daily records" ON public.daily_records;
DROP POLICY IF EXISTS "Users can delete own daily records" ON public.daily_records;

-- SELECT 策略
CREATE POLICY "Users can view own daily records"
  ON public.daily_records
  FOR SELECT
  USING (user_id = auth.uid());

-- INSERT 策略
CREATE POLICY "Users can insert own daily records"
  ON public.daily_records
  FOR INSERT
  WITH CHECK (user_id = auth.uid());

-- UPDATE 策略
CREATE POLICY "Users can update own daily records"
  ON public.daily_records
  FOR UPDATE
  USING (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid());

-- DELETE 策略
CREATE POLICY "Users can delete own daily records"
  ON public.daily_records
  FOR DELETE
  USING (user_id = auth.uid());

-- ============================================
-- 3. daily_record_items 表 RLS 策略
-- ============================================

-- 启用 RLS
ALTER TABLE public.daily_record_items ENABLE ROW LEVEL SECURITY;

-- 删除已存在的策略
DROP POLICY IF EXISTS "Users can view own daily record items" ON public.daily_record_items;
DROP POLICY IF EXISTS "Users can insert own daily record items" ON public.daily_record_items;
DROP POLICY IF EXISTS "Users can update own daily record items" ON public.daily_record_items;
DROP POLICY IF EXISTS "Users can delete own daily record items" ON public.daily_record_items;

-- SELECT 策略：通过 daily_records 间接验证
CREATE POLICY "Users can view own daily record items"
  ON public.daily_record_items
  FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM public.daily_records
      WHERE daily_records.id = daily_record_items.daily_record_id
      AND daily_records.user_id = auth.uid()
    )
  );

-- INSERT 策略
CREATE POLICY "Users can insert own daily record items"
  ON public.daily_record_items
  FOR INSERT
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.daily_records
      WHERE daily_records.id = daily_record_items.daily_record_id
      AND daily_records.user_id = auth.uid()
    )
  );

-- UPDATE 策略
CREATE POLICY "Users can update own daily record items"
  ON public.daily_record_items
  FOR UPDATE
  USING (
    EXISTS (
      SELECT 1 FROM public.daily_records
      WHERE daily_records.id = daily_record_items.daily_record_id
      AND daily_records.user_id = auth.uid()
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.daily_records
      WHERE daily_records.id = daily_record_items.daily_record_id
      AND daily_records.user_id = auth.uid()
    )
  );

-- DELETE 策略
CREATE POLICY "Users can delete own daily record items"
  ON public.daily_record_items
  FOR DELETE
  USING (
    EXISTS (
      SELECT 1 FROM public.daily_records
      WHERE daily_records.id = daily_record_items.daily_record_id
      AND daily_records.user_id = auth.uid()
    )
  );

-- ============================================
-- 4. diary_reviews 表 RLS 策略
-- ============================================

-- 启用 RLS
ALTER TABLE public.diary_reviews ENABLE ROW LEVEL SECURITY;

-- 删除已存在的策略
DROP POLICY IF EXISTS "Users can view own diary reviews" ON public.diary_reviews;
DROP POLICY IF EXISTS "Users can insert own diary reviews" ON public.diary_reviews;
DROP POLICY IF EXISTS "Users can update own diary reviews" ON public.diary_reviews;
DROP POLICY IF EXISTS "Users can delete own diary reviews" ON public.diary_reviews;

-- SELECT 策略
CREATE POLICY "Users can view own diary reviews"
  ON public.diary_reviews
  FOR SELECT
  USING (user_id = auth.uid());

-- INSERT 策略
CREATE POLICY "Users can insert own diary reviews"
  ON public.diary_reviews
  FOR INSERT
  WITH CHECK (user_id = auth.uid());

-- UPDATE 策略
CREATE POLICY "Users can update own diary reviews"
  ON public.diary_reviews
  FOR UPDATE
  USING (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid());

-- DELETE 策略
CREATE POLICY "Users can delete own diary reviews"
  ON public.diary_reviews
  FOR DELETE
  USING (user_id = auth.uid());

-- ============================================
-- 5. projects 表 RLS 策略
-- ============================================

-- 启用 RLS
ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;

-- 删除已存在的策略
DROP POLICY IF EXISTS "Users can view own projects" ON public.projects;
DROP POLICY IF EXISTS "Users can insert own projects" ON public.projects;
DROP POLICY IF EXISTS "Users can update own projects" ON public.projects;
DROP POLICY IF EXISTS "Users can delete own projects" ON public.projects;

-- SELECT 策略
CREATE POLICY "Users can view own projects"
  ON public.projects
  FOR SELECT
  USING (user_id = auth.uid());

-- INSERT 策略
CREATE POLICY "Users can insert own projects"
  ON public.projects
  FOR INSERT
  WITH CHECK (user_id = auth.uid());

-- UPDATE 策略
CREATE POLICY "Users can update own projects"
  ON public.projects
  FOR UPDATE
  USING (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid());

-- DELETE 策略
CREATE POLICY "Users can delete own projects"
  ON public.projects
  FOR DELETE
  USING (user_id = auth.uid());

-- ============================================
-- 6. project_logs 表 RLS 策略
-- ============================================

-- 启用 RLS
ALTER TABLE public.project_logs ENABLE ROW LEVEL SECURITY;

-- 删除已存在的策略
DROP POLICY IF EXISTS "Users can view own project logs" ON public.project_logs;
DROP POLICY IF EXISTS "Users can insert own project logs" ON public.project_logs;
DROP POLICY IF EXISTS "Users can update own project logs" ON public.project_logs;
DROP POLICY IF EXISTS "Users can delete own project logs" ON public.project_logs;

-- SELECT 策略：通过 projects 表间接验证
CREATE POLICY "Users can view own project logs"
  ON public.project_logs
  FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM public.projects
      WHERE projects.id = project_logs.project_id
      AND projects.user_id = auth.uid()
    )
  );

-- INSERT 策略
CREATE POLICY "Users can insert own project logs"
  ON public.project_logs
  FOR INSERT
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.projects
      WHERE projects.id = project_logs.project_id
      AND projects.user_id = auth.uid()
    )
  );

-- UPDATE 策略
CREATE POLICY "Users can update own project logs"
  ON public.project_logs
  FOR UPDATE
  USING (
    EXISTS (
      SELECT 1 FROM public.projects
      WHERE projects.id = project_logs.project_id
      AND projects.user_id = auth.uid()
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.projects
      WHERE projects.id = project_logs.project_id
      AND projects.user_id = auth.uid()
    )
  );

-- DELETE 策略
CREATE POLICY "Users can delete own project logs"
  ON public.project_logs
  FOR DELETE
  USING (
    EXISTS (
      SELECT 1 FROM public.projects
      WHERE projects.id = project_logs.project_id
      AND projects.user_id = auth.uid()
    )
  );

-- ============================================
-- 完成提示
-- ============================================
SELECT 'RLS 策略配置完成！已为 6 张核心表启用行级安全策略。' AS status;

-- ============================================================
-- sql/保留存档sql/sql1.0.1/003_add_profiles_table.sql
-- ============================================================

-- TETO 1.0
-- 003_add_profiles_table.sql
-- 作用：补齐缺失的 profiles 表，并配置 RLS

CREATE EXTENSION IF NOT EXISTS "pgcrypto";

CREATE TABLE IF NOT EXISTS public.profiles (
  id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  name text,
  avatar_url text,
  timezone text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "profiles_select_own" ON public.profiles;
CREATE POLICY "profiles_select_own"
ON public.profiles
FOR SELECT
USING (id = auth.uid());

DROP POLICY IF EXISTS "profiles_insert_own" ON public.profiles;
CREATE POLICY "profiles_insert_own"
ON public.profiles
FOR INSERT
WITH CHECK (id = auth.uid());

DROP POLICY IF EXISTS "profiles_update_own" ON public.profiles;
CREATE POLICY "profiles_update_own"
ON public.profiles
FOR UPDATE
USING (id = auth.uid())
WITH CHECK (id = auth.uid());

DROP POLICY IF EXISTS "profiles_delete_own" ON public.profiles;
CREATE POLICY "profiles_delete_own"
ON public.profiles
FOR DELETE
USING (id = auth.uid());

-- ============================================================
-- sql/保留存档sql/sql1.0.1/004_add_prediction_fields_to_projects.sql
-- ============================================================

-- ============================================
-- 004_add_prediction_fields_to_projects.sql
-- ============================================
-- 为 projects 表添加预测字段
-- 用于存储项目预计完成时间和剩余天数
-- ============================================

-- 添加 predicted_remaining_days 字段（预计剩余天数）
ALTER TABLE public.projects 
ADD COLUMN IF NOT EXISTS predicted_remaining_days INTEGER;

-- 添加 predicted_finish_date 字段（预计完成日期）
ALTER TABLE public.projects 
ADD COLUMN IF NOT EXISTS predicted_finish_date DATE;

-- 添加 updated_at 字段（如果不存在）
ALTER TABLE public.projects 
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, NOW());

-- 添加索引以优化查询性能
CREATE INDEX IF NOT EXISTS projects_user_status_idx 
  ON public.projects(user_id, status);

-- 添加注释
COMMENT ON COLUMN public.projects.predicted_remaining_days IS '预计剩余天数';
COMMENT ON COLUMN public.projects.predicted_finish_date IS '预计完成日期';
COMMENT ON COLUMN public.projects.updated_at IS '更新时间';

-- ============================================================
-- sql/保留存档sql/sql1.0.1/005_change_log_date_to_timestamp.sql
-- ============================================================

-- 将 project_logs.log_date 从 DATE 改为 TIMESTAMP WITH TIME ZONE，支持时分秒
-- 执行时间：2026-03-22

-- 1. 先删除旧索引
DROP INDEX IF EXISTS public.project_logs_log_date_idx;

-- 2. 修改 log_date 字段类型
ALTER TABLE public.project_logs 
  ALTER COLUMN log_date TYPE TIMESTAMP WITH TIME ZONE 
  USING log_date::timestamp with time zone;

-- 3. 重新创建索引
CREATE INDEX project_logs_log_date_idx ON public.project_logs(log_date);

-- 4. 更新字段注释
COMMENT ON COLUMN public.project_logs.log_date IS '日志日期时间（精确到秒）';

-- ============================================================
-- sql/保留存档sql/sql1.0.1/006_add_log_time_field.sql
-- ============================================================

-- 为 project_logs 表添加真正的日志时间字段 log_time
-- 执行时间：2026-03-22

-- 新增 log_time 字段（timestamp without time zone）
ALTER TABLE public.project_logs
  ADD COLUMN IF NOT EXISTS log_time timestamp without time zone;

-- 更新字段注释
COMMENT ON COLUMN public.project_logs.log_time IS '日志真实时间（精确到秒，用户输入的时间）';

-- 说明：
-- - log_date (date): 保留作为兼容字段，只存储日期
-- - log_time (timestamp without time zone): 新增字段，存储用户输入的完整时间（精确到秒）
-- - 新数据将使用 log_time 作为主时间字段
-- - 历史数据的 log_time 将为 NULL，log_date 保持原值

-- ============================================================
-- sql/保留存档sql/sql1.1-1.4/001_teto_1_3_records_model.sql
-- ============================================================

-- ============================================================
-- TETO 1.3 三页重构 · 核心记录模型建表脚本
-- 文件：009_teto_1_3_records_model.sql
-- 说明：TETO 1.3 三页重构（今日 / 事项 / 复盘）的核心数据表
--       包含 6 张表、2 个触发器、RLS 策略、索引
-- 创建顺序（按外键依赖）：
--   1. record_days  2. items  3. chains  4. records
--   5. tags  6. record_tags
-- ============================================================

-- ============================================================
-- 第一段：建表
-- ============================================================

-- -----------------------------------------------------------
-- 1. record_days —— 按天容器
-- -----------------------------------------------------------
CREATE TABLE IF NOT EXISTS record_days (
  id         UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id    UUID        NOT NULL REFERENCES auth.users(id),
  date       DATE        NOT NULL,
  summary    TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(user_id, date)
);

-- -----------------------------------------------------------
-- 2. items —— 事项（主题容器）
-- -----------------------------------------------------------
CREATE TABLE IF NOT EXISTS items (
  id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id     UUID        NOT NULL REFERENCES auth.users(id),
  title       TEXT        NOT NULL,
  description TEXT,
  status      TEXT        NOT NULL DEFAULT '活跃'
                          CHECK(status IN ('活跃','推进中','放缓','停滞','已完成','已搁置')),
  color       TEXT,
  icon        TEXT,
  started_at  TIMESTAMPTZ,
  ended_at    TIMESTAMPTZ,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- -----------------------------------------------------------
-- 3. chains —— 事件链（事项内部）
-- -----------------------------------------------------------
CREATE TABLE IF NOT EXISTS chains (
  id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id     UUID        NOT NULL REFERENCES auth.users(id),
  item_id     UUID        NOT NULL REFERENCES items(id) ON DELETE CASCADE,
  title       TEXT        NOT NULL,
  description TEXT,
  status      TEXT        NOT NULL DEFAULT '进行中'
                          CHECK(status IN ('进行中','已完成','已搁置')),
  started_at  TIMESTAMPTZ,
  ended_at    TIMESTAMPTZ,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- -----------------------------------------------------------
-- 4. records —— 记录项（最小单位）
-- -----------------------------------------------------------
CREATE TABLE IF NOT EXISTS records (
  id           UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id      UUID        NOT NULL REFERENCES auth.users(id),
  record_day_id UUID       NOT NULL REFERENCES record_days(id) ON DELETE CASCADE,
  content      TEXT        NOT NULL,
  type         TEXT        DEFAULT '发生'
                           CHECK(type IN ('发生','计划','情绪','想法','花费','总结','结果')),
  occurred_at  TIMESTAMPTZ,
  status       TEXT,
  mood         TEXT,
  energy       TEXT,
  result       TEXT,
  note         TEXT,
  item_id      UUID        REFERENCES items(id) ON DELETE SET NULL,
  chain_id     UUID        REFERENCES chains(id) ON DELETE SET NULL,
  sort_order   INTEGER     DEFAULT 0,
  is_starred   BOOLEAN     DEFAULT false,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- -----------------------------------------------------------
-- 5. tags —— 标签
-- -----------------------------------------------------------
CREATE TABLE IF NOT EXISTS tags (
  id         UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id    UUID        NOT NULL REFERENCES auth.users(id),
  name       TEXT        NOT NULL,
  color      TEXT,
  type       TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- -----------------------------------------------------------
-- 6. record_tags —— 记录-标签多对多
-- -----------------------------------------------------------
CREATE TABLE IF NOT EXISTS record_tags (
  id         UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id    UUID        NOT NULL REFERENCES auth.users(id),
  record_id  UUID        NOT NULL REFERENCES records(id) ON DELETE CASCADE,
  tag_id     UUID        NOT NULL REFERENCES tags(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(record_id, tag_id)
);

-- ============================================================
-- 第二段：触发器
-- ============================================================

-- -----------------------------------------------------------
-- chain/item 一致性触发器
-- 确保 records 的 chain_id 和 item_id 保持一致：
--   - 若 chain_id 非空且 item_id 为空，自动填充 chain 所属的 item_id
--   - 若 chain_id 非空且 item_id 非空但不匹配，抛出异常
-- -----------------------------------------------------------
CREATE OR REPLACE FUNCTION check_record_chain_item_consistency()
RETURNS TRIGGER AS $$
DECLARE
  v_chain_item_id UUID;
BEGIN
  IF NEW.chain_id IS NOT NULL THEN
    SELECT item_id INTO v_chain_item_id FROM chains WHERE id = NEW.chain_id;

    IF NOT FOUND THEN
      RAISE EXCEPTION 'chain_id % 不存在', NEW.chain_id;
    END IF;

    IF NEW.item_id IS NULL THEN
      NEW.item_id := v_chain_item_id;
    ELSIF NEW.item_id != v_chain_item_id THEN
      RAISE EXCEPTION 'record 的 item_id(%) 与 chain 所属的 item_id(%) 不一致',
        NEW.item_id, v_chain_item_id;
    END IF;
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_record_chain_item_consistency ON records;
CREATE TRIGGER trg_record_chain_item_consistency
  BEFORE INSERT OR UPDATE ON records
  FOR EACH ROW
  EXECUTE FUNCTION check_record_chain_item_consistency();

-- -----------------------------------------------------------
-- updated_at 自动更新触发器
-- -----------------------------------------------------------
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- record_days
DROP TRIGGER IF EXISTS trg_record_days_updated_at ON record_days;
CREATE TRIGGER trg_record_days_updated_at
  BEFORE UPDATE ON record_days
  FOR EACH ROW
  EXECUTE FUNCTION set_updated_at();

-- records
DROP TRIGGER IF EXISTS trg_records_updated_at ON records;
CREATE TRIGGER trg_records_updated_at
  BEFORE UPDATE ON records
  FOR EACH ROW
  EXECUTE FUNCTION set_updated_at();

-- items
DROP TRIGGER IF EXISTS trg_items_updated_at ON items;
CREATE TRIGGER trg_items_updated_at
  BEFORE UPDATE ON items
  FOR EACH ROW
  EXECUTE FUNCTION set_updated_at();

-- chains
DROP TRIGGER IF EXISTS trg_chains_updated_at ON chains;
CREATE TRIGGER trg_chains_updated_at
  BEFORE UPDATE ON chains
  FOR EACH ROW
  EXECUTE FUNCTION set_updated_at();

-- ============================================================
-- 第三段：RLS（行级安全策略）
-- ============================================================

-- -----------------------------------------------------------
-- record_days RLS
-- -----------------------------------------------------------
ALTER TABLE record_days ENABLE ROW LEVEL SECURITY;

CREATE POLICY record_days_select ON record_days
  FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY record_days_insert ON record_days
  FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY record_days_update ON record_days
  FOR UPDATE USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY record_days_delete ON record_days
  FOR DELETE USING (auth.uid() = user_id);

-- -----------------------------------------------------------
-- items RLS
-- -----------------------------------------------------------
ALTER TABLE items ENABLE ROW LEVEL SECURITY;

CREATE POLICY items_select ON items
  FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY items_insert ON items
  FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY items_update ON items
  FOR UPDATE USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY items_delete ON items
  FOR DELETE USING (auth.uid() = user_id);

-- -----------------------------------------------------------
-- chains RLS
-- -----------------------------------------------------------
ALTER TABLE chains ENABLE ROW LEVEL SECURITY;

CREATE POLICY chains_select ON chains
  FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY chains_insert ON chains
  FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY chains_update ON chains
  FOR UPDATE USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY chains_delete ON chains
  FOR DELETE USING (auth.uid() = user_id);

-- -----------------------------------------------------------
-- records RLS
-- -----------------------------------------------------------
ALTER TABLE records ENABLE ROW LEVEL SECURITY;

CREATE POLICY records_select ON records
  FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY records_insert ON records
  FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY records_update ON records
  FOR UPDATE USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY records_delete ON records
  FOR DELETE USING (auth.uid() = user_id);

-- -----------------------------------------------------------
-- tags RLS
-- -----------------------------------------------------------
ALTER TABLE tags ENABLE ROW LEVEL SECURITY;

CREATE POLICY tags_select ON tags
  FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY tags_insert ON tags
  FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY tags_update ON tags
  FOR UPDATE USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY tags_delete ON tags
  FOR DELETE USING (auth.uid() = user_id);

-- -----------------------------------------------------------
-- record_tags RLS
-- -----------------------------------------------------------
ALTER TABLE record_tags ENABLE ROW LEVEL SECURITY;

CREATE POLICY record_tags_select ON record_tags
  FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY record_tags_insert ON record_tags
  FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY record_tags_update ON record_tags
  FOR UPDATE USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY record_tags_delete ON record_tags
  FOR DELETE USING (auth.uid() = user_id);

-- ============================================================
-- 第四段：索引
-- ============================================================

-- record_days
CREATE INDEX IF NOT EXISTS idx_record_days_user_date ON record_days(user_id, date);

-- records
CREATE INDEX IF NOT EXISTS idx_records_user_day     ON records(user_id, record_day_id);
CREATE INDEX IF NOT EXISTS idx_records_user_occurred ON records(user_id, occurred_at);
CREATE INDEX IF NOT EXISTS idx_records_item          ON records(item_id);
CREATE INDEX IF NOT EXISTS idx_records_chain         ON records(chain_id);

-- items
CREATE INDEX IF NOT EXISTS idx_items_user_status     ON items(user_id, status);

-- chains
CREATE INDEX IF NOT EXISTS idx_chains_user_item      ON chains(user_id, item_id);

-- record_tags
CREATE INDEX IF NOT EXISTS idx_record_tags_record    ON record_tags(record_id);
CREATE INDEX IF NOT EXISTS idx_record_tags_tag       ON record_tags(tag_id);

-- ============================================================
-- sql/保留存档sql/sql1.1-1.4/002_drop_chain_structure.sql
-- ============================================================

-- ============================================================
-- TETO 1.3 · 删除 chain 相关结构迁移脚本
-- 文件：009_drop_chain_structure.sql
-- 说明：chain 概念正式删除后，清理数据库中所有 chain 相关结构
--       包括：触发器、外键字段、索引、RLS 策略、表
-- 执行顺序（先删依赖，后删主体）：
--   1. 删除 record_chain_item 一致性触发器
--   2. records 表删除 chain_id 字段
--   3. chains 表删除 RLS 策略
--   4. chains 表删除 updated_at 触发器
--   5. 删除 chains 表
--   6. 删除相关索引
-- ============================================================

-- -----------------------------------------------------------
-- 1. 删除 chain/item 一致性触发器
-- -----------------------------------------------------------
DROP TRIGGER IF EXISTS trg_record_chain_item_consistency ON records;
DROP FUNCTION IF EXISTS check_record_chain_item_consistency();

-- -----------------------------------------------------------
-- 2. records 表删除 chain_id 字段（外键引用 chains，需先删）
-- -----------------------------------------------------------
ALTER TABLE records DROP COLUMN IF EXISTS chain_id;

-- -----------------------------------------------------------
-- 3. chains 表删除 RLS 策略
-- -----------------------------------------------------------
DROP POLICY IF EXISTS chains_select ON chains;
DROP POLICY IF EXISTS chains_insert ON chains;
DROP POLICY IF EXISTS chains_update ON chains;
DROP POLICY IF EXISTS chains_delete ON chains;

-- -----------------------------------------------------------
-- 4. chains 表删除 updated_at 触发器
-- -----------------------------------------------------------
DROP TRIGGER IF EXISTS trg_chains_updated_at ON chains;

-- -----------------------------------------------------------
-- 5. 删除 chains 表
-- -----------------------------------------------------------
DROP TABLE IF EXISTS chains;

-- -----------------------------------------------------------
-- 6. 删除相关索引（如果存在）
-- -----------------------------------------------------------
DROP INDEX IF EXISTS idx_chains_user_item;
DROP INDEX IF EXISTS idx_records_chain;

-- ============================================================
-- sql/保留存档sql/sql1.1-1.4/003_teto_1_4_phases_and_goals.sql
-- ============================================================

-- ============================================================
-- TETO 1.4 阶段与目标模型建表脚本
-- 文件：003_teto_1_4_phases_and_goals.sql
-- 说明：新增 goals（目标）和 phases（阶段）两张核心表
--       并为 items 和 records 表添加 goal_id 外键关联
-- ============================================================


-- ============================================================
-- 第一段：建表
-- ============================================================

-- -----------------------------------------------------------
-- 1. goals —— 目标（方向层对象）
-- -----------------------------------------------------------
CREATE TABLE IF NOT EXISTS goals (
  id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id     UUID        NOT NULL REFERENCES auth.users(id),
  title       TEXT        NOT NULL,
  description TEXT,
  status      TEXT        NOT NULL DEFAULT '进行中'
                          CHECK(status IN ('进行中','已达成','已放弃','已暂停')),
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- -----------------------------------------------------------
-- 2. phases —— 阶段（事项在某段时间的持续现实概括）
-- -----------------------------------------------------------
CREATE TABLE IF NOT EXISTS phases (
  id            UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id       UUID        NOT NULL REFERENCES auth.users(id),
  item_id       UUID        NOT NULL REFERENCES items(id) ON DELETE CASCADE,
  goal_id       UUID        REFERENCES goals(id) ON DELETE SET NULL,
  title         TEXT        NOT NULL,
  description   TEXT,
  start_date    DATE,
  end_date      DATE,
  status        TEXT        NOT NULL DEFAULT '进行中'
                            CHECK(status IN ('进行中','已结束','停滞')),
  is_historical BOOLEAN     DEFAULT false,
  sort_order    INTEGER     DEFAULT 0,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ============================================================
-- 第二段：为现有表添加 goal_id 字段
-- ============================================================

-- -----------------------------------------------------------
-- 3. 为 items 表添加 goal_id 外键
-- -----------------------------------------------------------
ALTER TABLE items 
  ADD COLUMN IF NOT EXISTS goal_id UUID REFERENCES goals(id) ON DELETE SET NULL;

-- -----------------------------------------------------------
-- 4. 为 records 表添加 goal_id 外键
-- -----------------------------------------------------------
ALTER TABLE records 
  ADD COLUMN IF NOT EXISTS goal_id UUID REFERENCES goals(id) ON DELETE SET NULL;

-- ============================================================
-- 第三段：触发器（updated_at 自动更新）
-- ============================================================

-- goals 表 updated_at 触发器
DROP TRIGGER IF EXISTS trg_goals_updated_at ON goals;
CREATE TRIGGER trg_goals_updated_at
  BEFORE UPDATE ON goals
  FOR EACH ROW
  EXECUTE FUNCTION set_updated_at();

-- phases 表 updated_at 触发器
DROP TRIGGER IF EXISTS trg_phases_updated_at ON phases;
CREATE TRIGGER trg_phases_updated_at
  BEFORE UPDATE ON phases
  FOR EACH ROW
  EXECUTE FUNCTION set_updated_at();

-- ============================================================
-- 第四段：RLS（行级安全策略）
-- ============================================================

-- -----------------------------------------------------------
-- goals RLS
-- -----------------------------------------------------------
ALTER TABLE goals ENABLE ROW LEVEL SECURITY;

CREATE POLICY goals_select ON goals
  FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY goals_insert ON goals
  FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY goals_update ON goals
  FOR UPDATE USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY goals_delete ON goals
  FOR DELETE USING (auth.uid() = user_id);

-- -----------------------------------------------------------
-- phases RLS
-- -----------------------------------------------------------
ALTER TABLE phases ENABLE ROW LEVEL SECURITY;

CREATE POLICY phases_select ON phases
  FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY phases_insert ON phases
  FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY phases_update ON phases
  FOR UPDATE USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY phases_delete ON phases
  FOR DELETE USING (auth.uid() = user_id);

-- ============================================================
-- 第五段：索引
-- ============================================================

-- goals 表索引
CREATE INDEX IF NOT EXISTS idx_goals_user_status ON goals(user_id, status);

-- phases 表索引
CREATE INDEX IF NOT EXISTS idx_phases_user_item ON phases(user_id, item_id);
CREATE INDEX IF NOT EXISTS idx_phases_item ON phases(item_id);
CREATE INDEX IF NOT EXISTS idx_phases_goal ON phases(goal_id);

-- items 表新增索引
CREATE INDEX IF NOT EXISTS idx_items_goal ON items(goal_id);

-- records 表新增索引
CREATE INDEX IF NOT EXISTS idx_records_goal ON records(goal_id);

-- ============================================================
-- sql/保留存档sql/sql1.1-1.4/004_teto_1_4_record_type_convergence.sql
-- ============================================================

-- ============================================================
-- TETO 1.4 记录类型收敛
-- 新增 cost 字段（花费金额）
-- 收敛 type 为 4 个值：发生/计划/想法/总结
-- ============================================================

-- 1. 给 records 表新增 cost 字段
ALTER TABLE records ADD COLUMN cost NUMERIC(12,2) NULL;

-- 2. 创建 cost 字段索引（方便后续查询有花费的记录）
CREATE INDEX IF NOT EXISTS idx_records_cost ON records(cost) WHERE cost IS NOT NULL;

-- 3. 将旧类型记录迁移为主类型
--    情绪 → 发生，花费 → 发生，结果 → 发生
UPDATE records SET type = '发生' WHERE type IN ('情绪', '花费', '结果');

-- 4. 修改 type 的 CHECK 约束，只允许 4 个值
ALTER TABLE records DROP CONSTRAINT IF EXISTS records_type_check;
ALTER TABLE records ADD CONSTRAINT records_type_check CHECK (type IN ('发生', '计划', '想法', '总结'));

-- ============================================================
-- sql/保留存档sql/sql1.1-1.4/005_teto_1_4_status_chinese_migration.sql
-- ============================================================

-- ============================================================
-- TETO 1.4 阶段与目标状态中文化迁移脚本
-- 文件：005_teto_1_4_status_chinese_migration.sql
-- 说明：将 goals 和 phases 表的 status 从英文值迁移为中文值
--       并更新 CHECK 约束
-- ============================================================

-- ============================================================
-- 第一段：迁移 goals 表现有数据
-- ============================================================

UPDATE goals SET status = '进行中' WHERE status = 'active';
UPDATE goals SET status = '已达成' WHERE status = 'achieved';
UPDATE goals SET status = '已放弃' WHERE status = 'abandoned';
UPDATE goals SET status = '已暂停' WHERE status = 'paused';

-- 更新 goals 表的 CHECK 约束和默认值
ALTER TABLE goals DROP CONSTRAINT IF EXISTS goals_status_check;
ALTER TABLE goals ADD CONSTRAINT goals_status_check 
  CHECK(status IN ('进行中','已达成','已放弃','已暂停'));

ALTER TABLE goals ALTER COLUMN status SET DEFAULT '进行中';

-- ============================================================
-- 第二段：迁移 phases 表现有数据
-- ============================================================

UPDATE phases SET status = '进行中' WHERE status = 'active';
UPDATE phases SET status = '已结束' WHERE status IN ('completed', 'high_intensity', 'low_intensity');
UPDATE phases SET status = '停滞' WHERE status IN ('stagnant', 'recovery');

-- 更新 phases 表的 CHECK 约束和默认值
ALTER TABLE phases DROP CONSTRAINT IF EXISTS phases_status_check;
ALTER TABLE phases ADD CONSTRAINT phases_status_check 
  CHECK(status IN ('进行中','已结束','停滞'));

ALTER TABLE phases ALTER COLUMN status SET DEFAULT '进行中';

-- ============================================================
-- sql/保留存档sql/sql1.1-1.4/006_item_folders.sql
-- ============================================================

-- ============================================================
-- TETO 1.4 事项文件夹收纳功能
-- 文件：006_item_folders.sql
-- 说明：新增 item_folders 表，items 表增加 folder_id 字段
-- ============================================================

-- 1. 创建文件夹表
CREATE TABLE IF NOT EXISTS item_folders (
  id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id     UUID        NOT NULL REFERENCES auth.users(id),
  name        TEXT        NOT NULL,
  color       TEXT        DEFAULT NULL,
  sort_order  INTEGER     DEFAULT 0,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 2. items 表增加 folder_id 字段
ALTER TABLE items ADD COLUMN IF NOT EXISTS folder_id UUID REFERENCES item_folders(id) ON DELETE SET NULL;

-- 3. 文件夹触发器（自动更新 updated_at）
DROP TRIGGER IF EXISTS trg_item_folders_updated_at ON item_folders;
CREATE TRIGGER trg_item_folders_updated_at
  BEFORE UPDATE ON item_folders
  FOR EACH ROW
  EXECUTE FUNCTION set_updated_at();

-- 4. RLS
ALTER TABLE item_folders ENABLE ROW LEVEL SECURITY;
CREATE POLICY item_folders_select ON item_folders FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY item_folders_insert ON item_folders FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY item_folders_update ON item_folders FOR UPDATE USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY item_folders_delete ON item_folders FOR DELETE USING (auth.uid() = user_id);

-- 5. 索引
CREATE INDEX IF NOT EXISTS idx_item_folders_user ON item_folders(user_id);
CREATE INDEX IF NOT EXISTS idx_items_folder ON items(folder_id);

-- ============================================================
-- sql/保留存档sql/sql1.1-1.4/007_record_metric_fields.sql
-- ============================================================

-- ============================================================
-- TETO 1.4 记录结构化统计字段（最小版）
-- 文件：007_record_metric_fields.sql
-- 说明：给 records 表新增 metric_value / metric_unit / metric_name / duration_minutes
--       仅字段，不加索引；索引留到 P2/P3 确认查询路径后再补
-- ============================================================

-- 1. metric_value —— 数值（如 30、5、45）
ALTER TABLE records ADD COLUMN IF NOT EXISTS metric_value NUMERIC(12,2) NULL;

-- 2. metric_unit —— 计量单位（如 个、次、页、公里、分钟、元）
ALTER TABLE records ADD COLUMN IF NOT EXISTS metric_unit TEXT NULL;

-- 3. metric_name —— 统计对象，即"什么东西"（如 单词、俯卧撑、阅读、跑步距离）
--    注意与 unit 严格区分：name 是"什么东西"，unit 是"计量单位"
ALTER TABLE records ADD COLUMN IF NOT EXISTS metric_name TEXT NULL;

-- 4. duration_minutes —— 时长（分钟），独立于 metric 体系，记录行为持续时间
ALTER TABLE records ADD COLUMN IF NOT EXISTS duration_minutes INTEGER NULL;

-- ============================================================
-- sql/保留存档sql/sql1.1-1.4/008_add_raw_input_to_records.sql
-- ============================================================

-- ============================================================
-- TETO 1.4 记录原始输入字段
-- 文件：008_add_raw_input_to_records.sql
-- 说明：给 records 表新增 raw_input 字段
--       raw_input 存用户输入的原始自然语言（如"中午吃猪脚饭花了30块"）
--       content 继续存归类后的主题（如"午饭"），两条都保留，不丢信息
-- ============================================================

ALTER TABLE records ADD COLUMN IF NOT EXISTS raw_input TEXT;

COMMENT ON COLUMN records.raw_input IS '用户输入的原始自然语言文本，未经结构化处理';

-- ============================================================
-- sql/保留存档sql/sql1.1-1.4/008_record_links_and_batch.sql
-- ============================================================

-- ============================================================
-- TETO 1.4 Record 微关联 + 批次拆分 + 生命周期状态
-- 文件：008_record_links_and_batch.sql
-- ============================================================

-- 1. record_links 关联表（独立表 + 类型枚举）
CREATE TABLE record_links (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id),
  source_id UUID NOT NULL REFERENCES records(id) ON DELETE CASCADE,
  target_id UUID NOT NULL REFERENCES records(id) ON DELETE CASCADE,
  link_type TEXT NOT NULL CHECK (link_type IN (
    'completes',       -- source 完成了 target（计划→发生）
    'derived_from',    -- source 衍生自 target（同源拆分）
    'postponed_from',  -- source 是 target 的推迟版
    'related_to'       -- 通用双向关联
  )),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(source_id, target_id, link_type)
);
CREATE INDEX idx_record_links_source ON record_links(source_id);
CREATE INDEX idx_record_links_target ON record_links(target_id);

-- 2. records 表新增 batch_id（同一输入拆分出的记录共享）
ALTER TABLE records ADD COLUMN IF NOT EXISTS batch_id UUID NULL;
CREATE INDEX idx_records_batch_id ON records(batch_id) WHERE batch_id IS NOT NULL;

-- 3. records 表补充 lifecycle_status 列（生命周期状态，用于 Todo 流转）
-- 注意：records 表已有 status 列（进行中/已完成/已暂停），此处新增独立列避免冲突
ALTER TABLE records ADD COLUMN IF NOT EXISTS lifecycle_status TEXT DEFAULT 'active'
  CHECK (lifecycle_status IN ('active', 'completed', 'postponed', 'cancelled'));

-- ============================================================
-- sql/保留存档sql/sql1.1-1.4/009_teto_1_4_topic_module_upgrade.sql
-- ============================================================

-- ============================================================
-- TETO 1.4 事项（Topic）模块升级迁移脚本
-- 文件：009_teto_1_4_topic_module_upgrade.sql
-- 说明：
--   1. items 表新增 is_pinned（桌面置顶）
--   2. goals 表新增归属外键 item_id/phase_id + 度量字段
--   3. phases 表废除旧时代 goal_id（1.4 中 Goal 挂 Phase，非反向）
--   4. records 表新增 phase_id 外键
-- 安全原则：
--   - 所有新字段 nullable 或有合理默认值
--   - phases.goal_id 先置 NULL 再 drop，零数据丢失
--   - 全部使用 IF NOT EXISTS / IF EXISTS 保证幂等
-- ============================================================

-- ============================================================
-- 第一段：items 表升级
-- ============================================================

-- 1. 新增 is_pinned 字段（桌面置顶标记）
ALTER TABLE items ADD COLUMN IF NOT EXISTS is_pinned BOOLEAN DEFAULT false;

-- 2. 置顶事项查询索引（部分索引，仅 pinned=true 的行）
CREATE INDEX IF NOT EXISTS idx_items_pinned ON items(user_id, is_pinned) WHERE is_pinned = true;

-- ============================================================
-- 第二段：goals 表升级（归属 + 度量）
-- ============================================================

-- 3. 归属外键：目标属于哪个事项（允许 NULL，向后兼容全局目标）
ALTER TABLE goals ADD COLUMN IF NOT EXISTS item_id UUID REFERENCES items(id) ON DELETE CASCADE;

-- 4. 归属外键：目标属于哪个阶段（NULL = 事项级目标）
ALTER TABLE goals ADD COLUMN IF NOT EXISTS phase_id UUID REFERENCES phases(id) ON DELETE SET NULL;

-- 5. 度量类型：boolean（达标/未达标）或 numeric（量化型）
--    注意：ADD COLUMN IF NOT EXISTS 不支持同时加 CHECK，需分步
ALTER TABLE goals ADD COLUMN IF NOT EXISTS measure_type TEXT DEFAULT 'boolean';

-- 单独添加 CHECK 约束（幂等：先 DROP 再 ADD）
DO $$
BEGIN
  ALTER TABLE goals DROP CONSTRAINT IF EXISTS goals_measure_type_check;
  ALTER TABLE goals ADD CONSTRAINT goals_measure_type_check
    CHECK(measure_type IN ('boolean', 'numeric'));
EXCEPTION WHEN OTHERS THEN NULL;
END $$;

-- 6. 目标值（numeric 型时使用，如"背 5000 个单词"中的 5000）
ALTER TABLE goals ADD COLUMN IF NOT EXISTS target_value NUMERIC(12,2) NULL;

-- 7. 当前值（用户手动更新，绝不自动计算）
ALTER TABLE goals ADD COLUMN IF NOT EXISTS current_value NUMERIC(12,2) NULL;

-- 8. 索引
CREATE INDEX IF NOT EXISTS idx_goals_item ON goals(item_id);
CREATE INDEX IF NOT EXISTS idx_goals_phase ON goals(phase_id);

-- ============================================================
-- 第三段：phases 表清理（废除旧时代双向外键）
-- ============================================================
-- 1.4 中是 Goal 挂在 Phase 下（goals.phase_id → phases.id）
-- phases 不应再持有 goal_id，否则造成"双向绑定"脏关联

-- 9. 先将现有数据的 goal_id 安全置 NULL，再 DROP（幂等：列不存在时跳过）
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'phases' AND column_name = 'goal_id'
  ) THEN
    UPDATE phases SET goal_id = NULL WHERE goal_id IS NOT NULL;
    ALTER TABLE phases DROP COLUMN goal_id;
  END IF;
END $$;

-- 11. 清理对应的旧索引（如果存在）
DROP INDEX IF EXISTS idx_phases_goal;

-- ============================================================
-- 第四段：records 表升级
-- ============================================================

-- 12. 新增 phase_id 外键（记录可选归属某个阶段）
ALTER TABLE records ADD COLUMN IF NOT EXISTS phase_id UUID REFERENCES phases(id) ON DELETE SET NULL;

-- 13. 索引
CREATE INDEX IF NOT EXISTS idx_records_phase ON records(phase_id);

-- ============================================================
-- 完成
-- ============================================================
-- 验证要点：
--   SELECT column_name FROM information_schema.columns WHERE table_name='items' AND column_name='is_pinned';
--   SELECT column_name FROM information_schema.columns WHERE table_name='goals' AND column_name IN ('item_id','phase_id','measure_type','target_value','current_value');
--   SELECT column_name FROM information_schema.columns WHERE table_name='phases' AND column_name='goal_id'; -- 应返回空
--   SELECT column_name FROM information_schema.columns WHERE table_name='records' AND column_name='phase_id';

-- ============================================================
-- sql/保留存档sql/sql1.1-1.4/010_goal_benchmark_fields.sql
-- ============================================================

-- ============================================================
-- TETO 1.4 目标量化引擎 Benchmark 字段
-- 文件：010_goal_benchmark_fields.sql
-- 说明：为 goals 表新增 5 个量化引擎所需的 benchmark 配置字段
--       支持"金融账本式"差额计算：日均期望 × 天数 = 应当量，与实际量对比
-- 安全原则：
--   - 所有字段 nullable，向后兼容 measure_type=boolean 的非量化目标
--   - 全部使用 IF NOT EXISTS 保证幂等
-- ============================================================

-- 1. metric_name —— 关联指标名（如 '单词', '听读', '俯卧撑'）
--    用于精准匹配 records.metric_name，防止同事项下不同维度的记录串库
--    例：英语学习事项下，"词汇量"目标只统计 metric_name='单词' 的记录
ALTER TABLE goals ADD COLUMN IF NOT EXISTS metric_name TEXT NULL;

-- 2. unit —— 计量单位（如 '个', '分', '次', '页', '公里'）
--    独立于 records.metric_unit，属于 Goal 层面的标尺定义
ALTER TABLE goals ADD COLUMN IF NOT EXISTS unit TEXT NULL;

-- 3. daily_target —— 日均期望值（如 110）
--    引擎核心：合计应当 = total_passed_days × daily_target
ALTER TABLE goals ADD COLUMN IF NOT EXISTS daily_target NUMERIC(12,2) NULL;

-- 4. start_date —— 起算日（如 2024-12-23）
--    引擎核心：total_passed_days = today - start_date
ALTER TABLE goals ADD COLUMN IF NOT EXISTS start_date DATE NULL;

-- 5. deadline_date —— 截止日（可选，如 2026-12-31）
--    配速器用：dynamic_daily_pacer = (target_value - total_actual) / remaining_days
ALTER TABLE goals ADD COLUMN IF NOT EXISTS deadline_date DATE NULL;

-- ============================================================
-- 完成
-- ============================================================
-- 验证要点：
--   SELECT column_name FROM information_schema.columns
--   WHERE table_name='goals'
--   AND column_name IN ('metric_name','unit','daily_target','start_date','deadline_date');
--   -- 应返回 5 行

-- ============================================================
-- sql/保留存档sql/sql1.1-1.4/011_add_time_anchor_date.sql
-- ============================================================

-- ============================================================
-- 011: records 表添加 time_anchor_date 列 + 性能索引
--
-- time_anchor_date 允许计划类记录（type=计划）投影到未来的某个日期，
-- 在记录列表中按该日期查询时，可以提前看到未来的计划安排。
-- ============================================================

-- 1. time_anchor_date 列
ALTER TABLE records ADD COLUMN IF NOT EXISTS time_anchor_date DATE NULL;

COMMENT ON COLUMN records.time_anchor_date IS '计划投影日期：计划记录可在该日期被查询到';

CREATE INDEX IF NOT EXISTS idx_records_time_anchor
  ON records(time_anchor_date)
  WHERE time_anchor_date IS NOT NULL;

-- 2. 复合索引：按事项查记录（高频查询模式）
CREATE INDEX IF NOT EXISTS idx_records_user_item
  ON records(user_id, item_id)
  WHERE item_id IS NOT NULL;

-- 3. 复合索引：按类型过滤记录
CREATE INDEX IF NOT EXISTS idx_records_user_type
  ON records(user_id, type);

-- ============================================================
-- sql/保留存档sql/sql1.1-1.4/012_fix_goals_constraint.sql
-- ============================================================

-- ============================================================
-- 012: 修复 goals 表 measure_type 约束可能未生效的问题
--
-- 迁移 009 使用 EXCEPTION WHEN OTHERS THEN NULL 可能吞掉了
-- ADD CONSTRAINT 失败，导致 measure_type 列缺少 CHECK 约束。
-- 此迁移先修复异常数据，再重新添加约束。
-- ============================================================

-- 1. 清理非法值：将非 boolean/numeric 的值统一修正为 'numeric'
UPDATE goals SET measure_type = 'numeric'
  WHERE measure_type IS NULL
     OR measure_type NOT IN ('boolean', 'numeric');

-- 2. 确保约束存在（先删后建，幂等操作）
DO $$
BEGIN
  ALTER TABLE goals DROP CONSTRAINT IF EXISTS goals_measure_type_check;
EXCEPTION WHEN OTHERS THEN
  RAISE NOTICE '删除旧约束时出错（可能已不存在）';
END $$;

ALTER TABLE goals ADD CONSTRAINT goals_measure_type_check
  CHECK (measure_type IN ('boolean', 'numeric'));

-- ============================================================
-- sql/保留存档sql/sql1.1-1.4/013_record_semantic_fields.sql
-- ============================================================

-- ============================================================
-- 013: records 表补全语义解析持久化字段
--
-- TypeScript 接口 Record 中已定义以下 4 个字段，
-- 但数据库中缺少对应列，导致 Supabase .insert() 静默丢弃这些数据。
-- 此迁移补全缺失的列，使 AI 语义解析结果能够持久化。
-- ============================================================

-- 1. parsed_semantic —— AI 语义解析的完整 JSON 结果
ALTER TABLE records ADD COLUMN IF NOT EXISTS parsed_semantic JSONB NULL;

COMMENT ON COLUMN records.parsed_semantic IS 'AI 语义解析结果（DeepSeek LLM 输出的 ParsedSemantic JSON）';

-- 2. linked_record_id —— 单条记录的直接关联 ID（简化引用）
ALTER TABLE records ADD COLUMN IF NOT EXISTS linked_record_id UUID NULL;

COMMENT ON COLUMN records.linked_record_id IS '直接关联的记录 ID（简化引用，完整关联用 record_links 表）';

-- 3. location —— 地点信息
ALTER TABLE records ADD COLUMN IF NOT EXISTS location TEXT NULL;

COMMENT ON COLUMN records.location IS '地点（如"公司"、"公园"），由 AI 解析或手动输入';

-- 4. people —— 相关人物
ALTER TABLE records ADD COLUMN IF NOT EXISTS people TEXT[] NULL;

COMMENT ON COLUMN records.people IS '相关人物数组（如 ["小明", "同事"]），由 AI 解析或手动输入';

-- ============================================================
-- 索引（按需查询场景）
-- ============================================================

-- location 过滤索引（部分索引，仅非空行）
CREATE INDEX IF NOT EXISTS idx_records_location
  ON records(location)
  WHERE location IS NOT NULL;

-- people 数组包含查询索引（GIN 索引，支持 && 数组重叠查询）
CREATE INDEX IF NOT EXISTS idx_records_people
  ON records USING GIN (people)
  WHERE people IS NOT NULL;

-- ============================================================
-- sql/保留存档sql/sql1.1-1.4/014_sub_items_and_repeat_goals.sql
-- ============================================================

-- ============================================================
-- TETO 1.4 子项（Sub-Items）+ 重复型目标 迁移脚本
-- 文件：014_sub_items_and_repeat_goals.sql
-- 说明：
--   1. 新建 sub_items 表（事项下的行动线）
--   2. records 新增 sub_item_id 外键
--   3. goals 新增 sub_item_id 外键 + 重复型字段
--   4. goals.measure_type 扩展为 boolean/numeric/repeat
--   5. 修改 records.item_id FK 为 ON DELETE SET NULL（删除保护）
-- 安全原则：
--   - 所有新字段 nullable 或有合理默认值
--   - 全部使用 IF NOT EXISTS / IF EXISTS 保证幂等
--   - FK 变更使用独立 DO 块，失败不影响其他迁移
-- ============================================================

-- ============================================================
-- 第一段：创建 sub_items 表
-- ============================================================

CREATE TABLE IF NOT EXISTS sub_items (
  id            UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id       UUID        NOT NULL REFERENCES auth.users(id),
  item_id       UUID        NOT NULL REFERENCES items(id) ON DELETE CASCADE,
  title         TEXT        NOT NULL,
  description   TEXT,
  sort_order    INTEGER     DEFAULT 0,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- sub_items 索引
CREATE INDEX IF NOT EXISTS idx_sub_items_user ON sub_items(user_id);
CREATE INDEX IF NOT EXISTS idx_sub_items_item ON sub_items(item_id);
CREATE INDEX IF NOT EXISTS idx_sub_items_user_item ON sub_items(user_id, item_id);

-- ============================================================
-- 第二段：sub_items RLS
-- ============================================================

ALTER TABLE sub_items ENABLE ROW LEVEL SECURITY;

CREATE POLICY sub_items_select ON sub_items
  FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY sub_items_insert ON sub_items
  FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY sub_items_update ON sub_items
  FOR UPDATE USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY sub_items_delete ON sub_items
  FOR DELETE USING (auth.uid() = user_id);

-- ============================================================
-- 第三段：records 新增 sub_item_id
-- ============================================================

ALTER TABLE records ADD COLUMN IF NOT EXISTS sub_item_id UUID REFERENCES sub_items(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_records_sub_item ON records(sub_item_id);

-- ============================================================
-- 第四段：goals 新增 sub_item_id + 重复型字段
-- ============================================================

-- goals 归属子项
ALTER TABLE goals ADD COLUMN IF NOT EXISTS sub_item_id UUID REFERENCES sub_items(id) ON DELETE SET NULL;

-- 重复型目标字段
ALTER TABLE goals ADD COLUMN IF NOT EXISTS repeat_frequency TEXT;

-- repeat_frequency CHECK 约束（幂等：先 DROP 再 ADD）
DO $$
BEGIN
  ALTER TABLE goals DROP CONSTRAINT IF EXISTS goals_repeat_frequency_check;
  ALTER TABLE goals ADD CONSTRAINT goals_repeat_frequency_check
    CHECK(repeat_frequency IS NULL OR repeat_frequency IN ('daily', 'weekly', 'monthly'));
EXCEPTION WHEN OTHERS THEN NULL;
END $$;

ALTER TABLE goals ADD COLUMN IF NOT EXISTS repeat_count INTEGER;

-- goals 索引
CREATE INDEX IF NOT EXISTS idx_goals_sub_item ON goals(sub_item_id);

-- ============================================================
-- 第五段：goals.measure_type 扩展为包含 repeat
-- ============================================================

-- 先 DROP 旧约束，再 ADD 新约束
DO $$
BEGIN
  ALTER TABLE goals DROP CONSTRAINT IF EXISTS goals_measure_type_check;
  ALTER TABLE goals ADD CONSTRAINT goals_measure_type_check
    CHECK(measure_type IN ('boolean', 'numeric', 'repeat'));
EXCEPTION WHEN OTHERS THEN NULL;
END $$;

-- 将现有默认值 'boolean' 更新为新默认值（保持兼容）
-- 新建目标时默认使用 'boolean'，此处无需额外操作

-- ============================================================
-- 第六段：修改 records.item_id FK 为 ON DELETE SET NULL
-- ============================================================
-- 当前 records.item_id FK 无 ON DELETE 行为（默认 RESTRICT）
-- 需改为 SET NULL 以支持事项删除保护
-- Supabase/PostgreSQL 不能直接 ALTER CONSTRAINT，需先 DROP 再 ADD

DO $$
DECLARE
  fk_name TEXT;
BEGIN
  -- 查找 records(item_id) 上的外键约束名
  SELECT con.conname INTO fk_name
  FROM pg_constraint con
  JOIN pg_class rel ON rel.oid = con.conrelid
  JOIN pg_attribute att ON att.attrelid = rel.oid AND att.attnum = ANY(con.conkey)
  JOIN pg_class fk_rel ON fk_rel.oid = con.confrelid
  WHERE rel.relname = 'records'
    AND att.attname = 'item_id'
    AND con.contype = 'f'
  LIMIT 1;

  IF fk_name IS NOT NULL THEN
    EXECUTE format('ALTER TABLE records DROP CONSTRAINT %I', fk_name);
    EXECUTE 'ALTER TABLE records ADD CONSTRAINT records_item_id_fkey
             FOREIGN KEY (item_id) REFERENCES items(id) ON DELETE SET NULL';
  END IF;
END $$;

-- ============================================================
-- 第七段：updated_at 触发器（sub_items）
-- ============================================================

CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS set_updated_at ON sub_items;
CREATE TRIGGER set_updated_at
  BEFORE UPDATE ON sub_items
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

-- ============================================================
-- 完成
-- ============================================================
-- 验证要点：
--   SELECT column_name FROM information_schema.columns
--     WHERE table_name='sub_items' ORDER BY ordinal_position;
--   SELECT column_name FROM information_schema.columns
--     WHERE table_name='records' AND column_name='sub_item_id';
--   SELECT column_name FROM information_schema.columns
--     WHERE table_name='goals' AND column_name IN ('sub_item_id','repeat_frequency','repeat_count');
--   SELECT conname FROM pg_constraint WHERE conrelid = 'records'::regclass AND contype = 'f';

-- ============================================================
-- sql/保留存档sql/sql1.1-1.4/015_backfill_goals_item_id.sql
-- ============================================================

-- ============================================================
-- TETO 1.4 数据回填：将旧模型 goals 关系迁移到新模型
-- 文件：015_backfill_goals_item_id.sql
-- 说明：
--   旧模型：items.goal_id → goals.id（事项引用目标）
--   新模型：goals.item_id → items.id（目标引用事项）
--   此迁移将 items.goal_id 指向的目标回填 goals.item_id
--   执行后，所有目标都会通过 goals.item_id 关联到事项
-- 安全原则：
--   - 仅更新 item_id 为 NULL 的目标（不覆盖已有数据）
--   - 使用 EXISTS 确保引用完整性
--   - 幂等设计，可重复执行
-- ============================================================

-- 回填 goals.item_id：将 items.goal_id 指向的目标关联到对应事项
UPDATE goals g
SET item_id = i.id
FROM items i
WHERE i.goal_id = g.id
  AND g.item_id IS NULL
  AND i.goal_id IS NOT NULL;

-- 验证：
-- SELECT g.id, g.title, g.item_id, i.id as item_id_check
-- FROM goals g
-- JOIN items i ON i.goal_id = g.id
-- WHERE g.item_id = i.id;

-- ============================================================
-- sql/保留存档sql/sql1.5/001_drop_items_goal_id.sql
-- ============================================================

-- ============================================================
-- 1.5: 移除 items.goal_id 列
--
-- items.goal_id 是 1.4 之前的旧模型字段（事项→单目标），
-- 1.4 已改为 goals.item_id 反向关联（事项→多目标），
-- 1.5 正式移除此废弃字段。
--
-- 前置条件：
--   - 所有旧模型目标已通过 015_backfill_goals_item_id.sql 迁移
--     补全了 goals.item_id 字段
--   - 前端和 API 已不再引用 items.goal_id
-- ============================================================

-- 1. 先清理可能的残留外键约束
DO $$
DECLARE
  fk_name TEXT;
BEGIN
  SELECT con.conname INTO fk_name
  FROM pg_constraint con
  JOIN pg_class rel ON rel.oid = con.conrelid
  JOIN pg_attribute att ON att.attrelid = rel.oid AND att.attnum = ANY(con.conkey)
  WHERE rel.relname = 'items'
    AND att.attname = 'goal_id'
    AND con.contype = 'f'
  LIMIT 1;

  IF fk_name IS NOT NULL THEN
    EXECUTE format('ALTER TABLE items DROP CONSTRAINT %I', fk_name);
  END IF;
END $$;

-- 2. 移除 items.goal_id 列
ALTER TABLE items DROP COLUMN IF EXISTS goal_id;

-- ============================================================
-- 验证：
--   SELECT column_name FROM information_schema.columns
--     WHERE table_name = 'items' AND column_name = 'goal_id';
--   期望：0 rows
-- ============================================================

-- ============================================================
-- sql/保留存档sql/sql1.5/002_create_user_rules.sql
-- ============================================================

-- ============================================================
-- 1.5: 创建 user_rules 表
--
-- user_rules 承接用户修正后沉淀的归类规则，
-- 以及 AI 学习到的关键词→事项/子项映射。
--
-- 规则类型：
--   item_mapping     — 关键词→事项映射（如"背单词"→英语）
--   sub_item_mapping — 关键词→子项映射（如"听力"→英语.听读）
--   type_routing     — 关键词→记录类型分流（如"明天"→计划）
--   fuzzy_resolution — 常见模糊表达→默认解释
-- ============================================================

CREATE TABLE IF NOT EXISTS user_rules (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  rule_type TEXT NOT NULL CHECK (rule_type IN ('item_mapping', 'sub_item_mapping', 'type_routing', 'fuzzy_resolution')),
  trigger_pattern TEXT NOT NULL,           -- 触发模式（关键词/表达式）
  target_id UUID,                          -- 目标对象ID（事项/子项的ID）
  target_type TEXT,                        -- 'item' | 'sub_item'
  confidence TEXT DEFAULT 'high',          -- 'high' | 'medium' | 'low'
  source TEXT DEFAULT 'ai_learned',        -- 'ai_learned' | 'user_set' | 'system_default'
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- 索引：按用户+触发模式快速查找
CREATE INDEX IF NOT EXISTS idx_user_rules_user_trigger
  ON user_rules(user_id, trigger_pattern);

-- 索引：按用户+规则类型查找
CREATE INDEX IF NOT EXISTS idx_user_rules_user_type
  ON user_rules(user_id, rule_type);

-- 索引：按用户+活跃状态
CREATE INDEX IF NOT EXISTS idx_user_rules_user_active
  ON user_rules(user_id, is_active) WHERE is_active = true;

-- updated_at 自动更新触发器
CREATE OR REPLACE FUNCTION update_user_rules_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_user_rules_updated_at ON user_rules;
CREATE TRIGGER trg_user_rules_updated_at
  BEFORE UPDATE ON user_rules
  FOR EACH ROW
  EXECUTE FUNCTION update_user_rules_updated_at();

-- ============================================================
-- RLS 策略
-- ============================================================

ALTER TABLE user_rules ENABLE ROW LEVEL SECURITY;

-- 用户只能看自己的规则
CREATE POLICY "用户查看自己的规则"
  ON user_rules FOR SELECT
  USING (auth.uid() = user_id);

-- 用户只能插入自己的规则
CREATE POLICY "用户插入自己的规则"
  ON user_rules FOR INSERT
  WITH CHECK (auth.uid() = user_id);

-- 用户只能更新自己的规则
CREATE POLICY "用户更新自己的规则"
  ON user_rules FOR UPDATE
  USING (auth.uid() = user_id);

-- 用户只能删除自己的规则
CREATE POLICY "用户删除自己的规则"
  ON user_rules FOR DELETE
  USING (auth.uid() = user_id);

-- ============================================================
-- 验证：
--   SELECT * FROM user_rules WHERE user_id = auth.uid();
--   期望：返回当前用户的规则列表
-- ============================================================

-- ============================================================
-- sql/保留存档sql/sql1.5/003_period_rule_and_data_nature.sql
-- ============================================================

-- ============================================================
-- 1.5: 历史规律字段 + data_nature 数据性质标记
--
-- 为 records 表新增字段，支持：
-- 1. 概括性历史识别（规律记录 is_period_rule=true）
-- 2. 数据性质区分（data_nature: fact vs inferred）
-- 3. 规律记录的时间范围和频率信息
-- 4. 推断条目的来源关联
--
-- 前置条件：
--   - records 表已存在
--   - 013_record_semantic_fields.sql 已执行
-- ============================================================

-- 1. data_nature：区分原始事实记录 vs 推断生成的条目
ALTER TABLE records ADD COLUMN IF NOT EXISTS data_nature TEXT DEFAULT 'fact'
  CHECK (data_nature IN ('fact', 'inferred'));
COMMENT ON COLUMN records.data_nature IS '数据性质：fact=原始事实记录, inferred=由概括性规律推断生成的条目';

-- 2. is_period_rule：标记是否为规律记录
ALTER TABLE records ADD COLUMN IF NOT EXISTS is_period_rule BOOLEAN DEFAULT false;
COMMENT ON COLUMN records.is_period_rule IS '是否为概括性规律记录（如"那段时间基本每天7:40起床"）';

-- 3. period_start_date：规律起始日
ALTER TABLE records ADD COLUMN IF NOT EXISTS period_start_date DATE;
COMMENT ON COLUMN records.period_start_date IS '规律记录的时间范围起始日';

-- 4. period_end_date：规律结束日
ALTER TABLE records ADD COLUMN IF NOT EXISTS period_end_date DATE;
COMMENT ON COLUMN records.period_end_date IS '规律记录的时间范围结束日';

-- 5. period_frequency：规律频率
ALTER TABLE records ADD COLUMN IF NOT EXISTS period_frequency TEXT
  CHECK (period_frequency IS NULL OR period_frequency IN ('daily', 'weekly', 'monthly', 'irregular'));
COMMENT ON COLUMN records.period_frequency IS '规律频率：daily/weekly/monthly/irregular';

-- 6. period_expanded：规律是否已展开
ALTER TABLE records ADD COLUMN IF NOT EXISTS period_expanded BOOLEAN DEFAULT false;
COMMENT ON COLUMN records.period_expanded IS '规律记录是否已展开为逐日推断条目';

-- 7. period_source_id：推断条目的来源规律记录ID
ALTER TABLE records ADD COLUMN IF NOT EXISTS period_source_id UUID
  REFERENCES records(id) ON DELETE SET NULL;
COMMENT ON COLUMN records.period_source_id IS '推断条目(data_nature=inferred)的来源规律记录ID';

-- ============================================================
-- 索引
-- ============================================================

-- 按用户+数据性质查找（统计时过滤推断数据）
CREATE INDEX IF NOT EXISTS idx_records_data_nature
  ON records(data_nature) WHERE data_nature != 'fact';

-- 按规律记录查找
CREATE INDEX IF NOT EXISTS idx_records_period_rule
  ON records(is_period_rule) WHERE is_period_rule = true;

-- 按来源规律查找推断条目
CREATE INDEX IF NOT EXISTS idx_records_period_source
  ON records(period_source_id) WHERE period_source_id IS NOT NULL;

-- ============================================================
-- 验证：
--   SELECT column_name, data_type FROM information_schema.columns
--     WHERE table_name = 'records'
--       AND column_name IN ('data_nature', 'is_period_rule', 'period_start_date', 'period_end_date', 'period_frequency', 'period_expanded', 'period_source_id');
--   期望：7 rows
-- ============================================================

-- ============================================================
-- sql/保留存档sql/sql1.5/004_record_backbone_fields.sql
-- ============================================================

-- ============================================================
-- 004: records 表三层九组模型 — Phase 1 主链补齐
--
-- 新增 18 个列，补齐"时间 → 发生 → 状态 → 结果"主链，
-- 让记录可独立统计，解决主链断裂、字段混层、统计口径不稳。
--
-- 枚举原则：DB 存英文，前端通过 *_LABELS 映射中文。
-- 前置条件：records 表已存在，003_period_rule_and_data_nature.sql 已执行。
-- ============================================================

-- ============================================================
-- L2-B 时间组
-- ============================================================

-- 1. occurred_at_end —— 结束时间
ALTER TABLE records ADD COLUMN IF NOT EXISTS occurred_at_end TIMESTAMPTZ;
COMMENT ON COLUMN records.occurred_at_end IS '结束时间（与 occurred_at 配对，可空）';

-- 2. time_text —— 原文时间表达
ALTER TABLE records ADD COLUMN IF NOT EXISTS time_text TEXT;
COMMENT ON COLUMN records.time_text IS '原文时间表达（如"昨晚"、"下班路上"、"今天早上"）';

-- 3. time_precision —— 时间精度
ALTER TABLE records ADD COLUMN IF NOT EXISTS time_precision TEXT
  CHECK(time_precision IS NULL OR time_precision IN ('exact','approx','fuzzy','unknown'));
COMMENT ON COLUMN records.time_precision IS '时间精度：exact=精确, approx=大约, fuzzy=模糊, unknown=未知';

-- ============================================================
-- L2-D 发生主干组（核心新增）
-- ============================================================

-- 4. action_text —— 实际动作
ALTER TABLE records ADD COLUMN IF NOT EXISTS action_text TEXT;
COMMENT ON COLUMN records.action_text IS '实际动作（如"开会"、"躺着"、"通勤"、"买咖啡"）';

-- 5. event_text —— 事件表达
ALTER TABLE records ADD COLUMN IF NOT EXISTS event_text TEXT;
COMMENT ON COLUMN records.event_text IS '事件表达（如"会议太长"、"地铁太挤"、"被客户改需求"）';

-- 6. object_text —— 动作/事件指向对象
ALTER TABLE records ADD COLUMN IF NOT EXISTS object_text TEXT;
COMMENT ON COLUMN records.object_text IS '动作或事件指向的对象（如"会议"、"咖啡"、"地铁"、"手机"）';

-- ============================================================
-- L2-G 结果组
-- ============================================================

-- 7. outcome_type —— 结果类型（英文枚举）
ALTER TABLE records ADD COLUMN IF NOT EXISTS outcome_type TEXT
  CHECK(outcome_type IS NULL OR outcome_type IN ('done','progress','recovered','maintained','interrupted','stagnant','consumed','deviated','no_change'));
COMMENT ON COLUMN records.outcome_type IS '结果类型：done=完成, progress=推进, recovered=恢复, maintained=维持, interrupted=被打断, stagnant=停滞, consumed=消耗, deviated=偏离, no_change=无明显结果';

-- 8. outcome_direction —— 结果方向（英文枚举）
ALTER TABLE records ADD COLUMN IF NOT EXISTS outcome_direction TEXT
  CHECK(outcome_direction IS NULL OR outcome_direction IN ('positive','neutral','negative'));
COMMENT ON COLUMN records.outcome_direction IS '结果方向：positive=正向, neutral=中性, negative=负向';

-- ============================================================
-- L2-F 因果组
-- ============================================================

-- 9. cause_text —— 原因
ALTER TABLE records ADD COLUMN IF NOT EXISTS cause_text TEXT;
COMMENT ON COLUMN records.cause_text IS '原因（如"因为昨晚没睡好"、"因为会议太长"）';

-- ============================================================
-- L2-H 地点组
-- ============================================================

-- 10. place_type —— 地点类型（英文枚举）
ALTER TABLE records ADD COLUMN IF NOT EXISTS place_type TEXT
  CHECK(place_type IS NULL OR place_type IN ('home','office','commuting','transport','shop','hospital','school','outdoor','online','other'));
COMMENT ON COLUMN records.place_type IS '地点类型：home=家, office=公司, commuting=路上, transport=交通中, shop=店铺, hospital=医院, school=学校, outdoor=户外, online=线上, other=其他';

-- ============================================================
-- L2-I 量化组
-- ============================================================

-- 11. money_direction —— 资金方向（英文枚举）
ALTER TABLE records ADD COLUMN IF NOT EXISTS money_direction TEXT
  CHECK(money_direction IS NULL OR money_direction IN ('expense','income','none'));
COMMENT ON COLUMN records.money_direction IS '资金方向：expense=支出, income=收入, none=无';

-- 12. metrics —— 多指标数组（默认空数组）
ALTER TABLE records ADD COLUMN IF NOT EXISTS metrics JSONB DEFAULT '[]'::jsonb;
COMMENT ON COLUMN records.metrics IS '量化指标数组，格式: [{"name":"时长","value":40,"unit":"分钟"},{"name":"步数","value":6000,"unit":"步"}]，默认空数组 []';

-- ============================================================
-- L2-H 人物组补充
-- ============================================================

-- 13. relation_roles —— 关系角色数组
ALTER TABLE records ADD COLUMN IF NOT EXISTS relation_roles TEXT[];
COMMENT ON COLUMN records.relation_roles IS '关系角色数组（如 ["同事","家人","客户","朋友","领导"]），与 people 互补';

-- ============================================================
-- L3-J 组织组
-- ============================================================

-- 14. review_status —— 审核状态（英文枚举）
ALTER TABLE records ADD COLUMN IF NOT EXISTS review_status TEXT DEFAULT 'unchecked'
  CHECK(review_status IN ('unchecked','confirmed','corrected'));
COMMENT ON COLUMN records.review_status IS '审核状态：unchecked=未检查, confirmed=已确认, corrected=已纠错';

-- 15. confidence_level —— AI 提取可信度（英文枚举）
ALTER TABLE records ADD COLUMN IF NOT EXISTS confidence_level TEXT
  CHECK(confidence_level IS NULL OR confidence_level IN ('low','medium','high'));
COMMENT ON COLUMN records.confidence_level IS 'AI 提取可信度：low=低, medium=中, high=高';

-- ============================================================
-- L1-A 原始层
-- ============================================================

-- 16. input_source —— 输入来源
ALTER TABLE records ADD COLUMN IF NOT EXISTS input_source TEXT DEFAULT 'manual'
  CHECK(input_source IN ('manual','ai','quick','edit','import'));
COMMENT ON COLUMN records.input_source IS '输入来源：manual=手动, ai=AI生成, quick=快速录入, edit=编辑, import=导入';

-- ============================================================
-- RECORD_TYPE 扩展：补齐 DB CHECK 与 TS 枚举的对齐
-- DB 侧 1.3 建表时已有 7 种 CHECK，但 TS 侧只暴露了 4 种。
-- 此处不改动 DB（已有完整 CHECK），仅由 TS 侧补齐。
-- ============================================================
-- 注意：1.3 建表 SQL 中 type 的 CHECK 已包含：
--   '发生','计划','情绪','想法','花费','总结','结果'
-- 无需 ALTER。TS 侧将同步扩展。

-- ============================================================
-- 索引
-- ============================================================

-- outcome_type 索引（统计查询高频）
CREATE INDEX IF NOT EXISTS idx_records_outcome_type
  ON records(outcome_type) WHERE outcome_type IS NOT NULL;

-- place_type 索引
CREATE INDEX IF NOT EXISTS idx_records_place_type
  ON records(place_type) WHERE place_type IS NOT NULL;

-- review_status 索引
CREATE INDEX IF NOT EXISTS idx_records_review_status
  ON records(review_status) WHERE review_status != 'unchecked';

-- input_source 索引
CREATE INDEX IF NOT EXISTS idx_records_input_source
  ON records(input_source) WHERE input_source != 'manual';

-- ============================================================
-- 验证：
--   SELECT column_name, data_type, column_default
--     FROM information_schema.columns
--     WHERE table_name = 'records'
--       AND column_name IN (
--         'occurred_at_end','time_text','time_precision',
--         'action_text','event_text','object_text',
--         'outcome_type','outcome_direction',
--         'cause_text','place_type',
--         'money_direction','metrics',
--         'relation_roles',
--         'review_status','confidence_level',
--         'input_source'
--       )
--     ORDER BY ordinal_position;
--   期望：16 rows
-- ============================================================

-- ============================================================
-- sql/保留存档sql/sql1.5/004b_record_alignment.sql
-- ============================================================

-- ============================================================
-- 1.5 录入结构正式对齐：新增 body_state、money_currency 列
--
-- 变更说明：
-- 1. body_state: 身体状态（累/困/饿/头疼/没精神），
--    解决"累"被误归入 energy 的问题
-- 2. money_currency: 金额币种（默认 CNY），配套 cost 字段
--
-- 前置条件：
--   - records 表已存在
--   - 003_period_rule_and_data_nature.sql 已执行
-- ============================================================

-- 1. body_state：身体状态
ALTER TABLE records ADD COLUMN IF NOT EXISTS body_state TEXT;
COMMENT ON COLUMN records.body_state IS '身体状态：累/困/饿/头疼/没精神等，与 mood/energy/state 分离';

-- 2. money_currency：金额币种
ALTER TABLE records ADD COLUMN IF NOT EXISTS money_currency TEXT DEFAULT 'CNY';
COMMENT ON COLUMN records.money_currency IS '金额币种，默认 CNY，与 cost 配套使用';

-- ============================================================
-- 验证：
--   SELECT column_name, data_type, column_default
--     FROM information_schema.columns
--       WHERE table_name = 'records'
--         AND column_name IN ('body_state', 'money_currency');
--   期望：2 rows
-- ============================================================

-- ============================================================
-- sql/保留存档sql/sql1.5/005_record_type_converge_to_four.sql
-- ============================================================

-- 005: 记录类型收敛 — 情绪/花费/结果 归并为 发生
-- RECORD_TYPES 从 7 种收敛为 4 种：发生、计划、想法、总结
-- 情绪/花费/结果 不再作为主类型，降级为附属属性

-- 1. 将旧类型记录归并为'发生'
UPDATE records SET type = '发生' WHERE type IN ('情绪', '花费', '结果');

-- 2. 添加 CHECK 约束（可选，防止未来再写入旧类型）
ALTER TABLE records DROP CONSTRAINT IF EXISTS records_type_check;
ALTER TABLE records ADD CONSTRAINT records_type_check
  CHECK (type IN ('发生', '计划', '想法', '总结'));

-- ============================================================
-- sql/保留存档sql/sql1.5/006_goal_rule_refactor.sql
-- ============================================================

-- ============================================================
-- 006: 目标系统规则重构
-- 将 measure_type(boolean/numeric/repeat) 迁移为
-- rule_type(一次性完成/周期性达成/周期性限制) + operator + period
-- ============================================================

-- ──────────────────────────────────────────
-- 阶段一：新增字段
-- ──────────────────────────────────────────

ALTER TABLE goals ADD COLUMN IF NOT EXISTS goal_text TEXT;
ALTER TABLE goals ADD COLUMN IF NOT EXISTS rule_type TEXT
  CHECK (rule_type IN ('一次性完成', '周期性达成', '周期性限制'));
ALTER TABLE goals ADD COLUMN IF NOT EXISTS operator TEXT
  CHECK (operator IN ('>=', '<=', '=', 'between', 'before', 'after', 'complete'));
ALTER TABLE goals ADD COLUMN IF NOT EXISTS period TEXT
  CHECK (period IN ('无', '每天', '每周', '每月', '每年', '本周', '本月'));
ALTER TABLE goals ADD COLUMN IF NOT EXISTS target_min NUMERIC;
ALTER TABLE goals ADD COLUMN IF NOT EXISTS target_max NUMERIC;
ALTER TABLE goals ADD COLUMN IF NOT EXISTS deadline DATE;
ALTER TABLE goals ADD COLUMN IF NOT EXISTS end_date DATE;
ALTER TABLE goals ADD COLUMN IF NOT EXISTS source TEXT DEFAULT '手动创建'
  CHECK (source IN ('手动创建', '从记录生成', '系统建议'));
ALTER TABLE goals ADD COLUMN IF NOT EXISTS confirmation_required BOOLEAN DEFAULT false;
ALTER TABLE goals ADD COLUMN IF NOT EXISTS progress_source TEXT DEFAULT '记录统计'
  CHECK (progress_source IN ('记录统计', '手动更新', '暂无'));

-- ──────────────────────────────────────────
-- 阶段二：数据迁移
-- ──────────────────────────────────────────

-- 1. boolean 达标型 → 一次性完成 (operator=complete)
UPDATE goals SET
  rule_type = '一次性完成',
  operator = 'complete',
  period = '无',
  target_min = target_value,
  target_max = target_value,
  goal_text = title,
  source = '手动创建',
  progress_source = '手动更新',
  confirmation_required = false
WHERE measure_type = 'boolean'
  AND rule_type IS NULL;

-- 2. numeric 量化型(有 deadline) → 一次性完成 (operator=>=)
UPDATE goals SET
  rule_type = '一次性完成',
  operator = '>=',
  period = '无',
  target_min = target_value,
  target_max = NULL,
  goal_text = title,
  source = '手动创建',
  progress_source = '记录统计',
  confirmation_required = false,
  deadline = deadline_date
WHERE measure_type = 'numeric'
  AND deadline_date IS NOT NULL
  AND rule_type IS NULL;

-- 3. numeric 量化型(有 daily_target, 无 deadline) → 周期性达成
UPDATE goals SET
  rule_type = '周期性达成',
  operator = '>=',
  period = '每天',
  target_min = daily_target,
  target_max = NULL,
  goal_text = title,
  source = '手动创建',
  progress_source = '记录统计',
  confirmation_required = false
WHERE measure_type = 'numeric'
  AND daily_target IS NOT NULL
  AND deadline_date IS NULL
  AND rule_type IS NULL;

-- 4. repeat 重复型 → 周期性达成
UPDATE goals SET
  rule_type = '周期性达成',
  operator = '>=',
  period = CASE repeat_frequency
    WHEN 'daily' THEN '每天'
    WHEN 'weekly' THEN '每周'
    WHEN 'monthly' THEN '每月'
    ELSE '每天'
  END,
  target_min = repeat_count,
  target_max = NULL,
  goal_text = title,
  source = '手动创建',
  progress_source = '记录统计',
  confirmation_required = false,
  unit = COALESCE(unit, '次')
WHERE measure_type = 'repeat'
  AND rule_type IS NULL;

-- 5. 兜底：仍未迁移的 numeric 目标（无 daily_target 也无 deadline）
UPDATE goals SET
  rule_type = '一次性完成',
  operator = '>=',
  period = '无',
  target_min = target_value,
  goal_text = title,
  source = '手动创建',
  progress_source = CASE WHEN target_value IS NOT NULL THEN '记录统计' ELSE '手动更新' END,
  confirmation_required = false
WHERE measure_type = 'numeric'
  AND rule_type IS NULL;

-- 6. 状态映射：已达成 → 已完成
UPDATE goals SET status = '已完成' WHERE status = '已达成';

-- 7. 扩展 status 约束，新增草稿状态
ALTER TABLE goals DROP CONSTRAINT IF EXISTS goals_status_check;
ALTER TABLE goals ADD CONSTRAINT goals_status_check
  CHECK (status IN ('草稿', '进行中', '已完成', '暂停', '放弃'));

-- 8. 同步 target_value = target_min（确保一致性）
UPDATE goals SET target_value = target_min WHERE target_value IS NULL AND target_min IS NOT NULL;

-- ──────────────────────────────────────────
-- 阶段三：删除旧字段
-- ──────────────────────────────────────────

ALTER TABLE goals DROP COLUMN IF EXISTS measure_type;
ALTER TABLE goals DROP COLUMN IF EXISTS repeat_frequency;
ALTER TABLE goals DROP COLUMN IF EXISTS repeat_count;
ALTER TABLE goals DROP COLUMN IF EXISTS daily_target;
ALTER TABLE goals DROP COLUMN IF EXISTS deadline_date;

-- ──────────────────────────────────────────
-- 阶段四：新增索引
-- ──────────────────────────────────────────

CREATE INDEX IF NOT EXISTS idx_goals_item_status ON goals(user_id, item_id, status);
CREATE INDEX IF NOT EXISTS idx_goals_rule_type ON goals(user_id, rule_type);

-- ============================================================
-- sql/保留存档sql/sql1.5/007_add_performance_indexes.sql
-- ============================================================

-- 007: 补齐 records/goals/phases/items 表的 user_id 复合索引
-- 当前活跃迁移中 records 表缺少 user_id 索引，phases 表完全没有索引
-- 使用 CREATE INDEX IF NOT EXISTS 保证幂等

-- records 表（最高频查询）
CREATE INDEX IF NOT EXISTS idx_records_user_item ON records(user_id, item_id) WHERE item_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_records_user_sub_item ON records(user_id, sub_item_id) WHERE sub_item_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_records_user_phase ON records(user_id, phase_id) WHERE phase_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_records_user_time_anchor ON records(user_id, time_anchor_date) WHERE time_anchor_date IS NOT NULL;

-- goals 表
CREATE INDEX IF NOT EXISTS idx_goals_user_phase ON goals(user_id, phase_id) WHERE phase_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_goals_user_sub_item ON goals(user_id, sub_item_id) WHERE sub_item_id IS NOT NULL;

-- phases 表
CREATE INDEX IF NOT EXISTS idx_phases_user_status ON phases(user_id, status);

-- items 表
CREATE INDEX IF NOT EXISTS idx_items_user_folder ON items(user_id, folder_id) WHERE folder_id IS NOT NULL;

-- ── 清理被复合索引覆盖的旧弱索引（缺少 user_id，RLS 下无效） ──
DROP INDEX IF EXISTS idx_records_item;        -- 被 idx_records_user_item 覆盖
DROP INDEX IF EXISTS idx_records_phase;       -- 被 idx_records_user_phase 覆盖
DROP INDEX IF EXISTS idx_records_sub_item;    -- 被 idx_records_user_sub_item 覆盖
DROP INDEX IF EXISTS idx_records_time_anchor; -- 被 idx_records_user_time_anchor 覆盖
DROP INDEX IF EXISTS idx_goals_item;          -- 被 idx_goals_item_status 覆盖
DROP INDEX IF EXISTS idx_goals_phase;         -- 被 idx_goals_user_phase 覆盖
DROP INDEX IF EXISTS idx_goals_sub_item;      -- 被 idx_goals_user_sub_item 覆盖
