-- Bootstrap 003: sql/016–040 incremental migrations
-- Generated by scripts/build-bootstrap-sql.mjs — do not edit by hand

-- ============================================================
-- sql/016_corrections.sql
-- ============================================================

-- 016_corrections.sql
-- TETO 1.6 — 用户纠错记录表
-- 每次用户修正 AI 推断字段时生成一条记录，绑定原 decision_id

CREATE TABLE IF NOT EXISTS corrections (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  record_id UUID NOT NULL REFERENCES records(id) ON DELETE CASCADE,
  decision_id TEXT NOT NULL,              -- 被修正的决策 ID，如 DEC-ITEM-xxx
  field_corrected TEXT NOT NULL,          -- 被修正的字段名，如 item_id
  old_value TEXT,                         -- 修正前的值
  new_value TEXT,                         -- 修正后的值
  corrected_by TEXT NOT NULL DEFAULT 'user', -- 'user' | 'system'
  trace_id TEXT,                          -- 关联的 trace_id
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 索引
CREATE INDEX IF NOT EXISTS idx_corrections_record_id ON corrections(record_id);
CREATE INDEX IF NOT EXISTS idx_corrections_decision_id ON corrections(decision_id);
CREATE INDEX IF NOT EXISTS idx_corrections_created_at ON corrections(created_at);

-- RLS
ALTER TABLE corrections ENABLE ROW LEVEL SECURITY;

-- 用户只能看到自己的记录的纠错
DROP POLICY IF EXISTS corrections_user_policy ON corrections;
CREATE POLICY corrections_user_policy ON corrections
  FOR ALL
  USING (
    record_id IN (
      SELECT id FROM records WHERE user_id = auth.uid()
    )
  );

-- ============================================================
-- sql/017_trace_summaries.sql
-- ============================================================

-- 017_trace_summaries.sql
-- TETO 1.6 可观测性：trace 摘要表
-- 存储每次 API 操作/管道执行的 trace 摘要
-- 自动清理：保留 7 天（通过应用层定时任务或 Supabase pg_cron）

CREATE TABLE IF NOT EXISTS trace_summaries (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  trace_id TEXT NOT NULL,
  user_id UUID,
  operation TEXT,                -- e.g. 'record_create', 'goal_compute', 'parse'
  status TEXT NOT NULL DEFAULT 'ok',  -- 'ok' | 'failed' | 'partial'
  total_duration_ms INTEGER,
  span_count INTEGER DEFAULT 0,
  error_code TEXT,
  error_message TEXT,
  input_summary TEXT,
  output_summary TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- 索引
CREATE INDEX IF NOT EXISTS idx_trace_summaries_trace_id ON trace_summaries(trace_id);
CREATE INDEX IF NOT EXISTS idx_trace_summaries_user_id ON trace_summaries(user_id);
CREATE INDEX IF NOT EXISTS idx_trace_summaries_created_at ON trace_summaries(created_at);
CREATE INDEX IF NOT EXISTS idx_trace_summaries_status ON trace_summaries(status);

-- RLS
ALTER TABLE trace_summaries ENABLE ROW LEVEL SECURITY;

-- 用户只能查看自己的 trace
CREATE POLICY "Users can view own traces"
  ON trace_summaries FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own traces"
  ON trace_summaries FOR INSERT
  WITH CHECK (auth.uid() = user_id);

-- 通过 service_role 允许系统写入（无需 user_id 验证）
CREATE POLICY "Service can manage all traces"
  ON trace_summaries FOR ALL
  USING (true)
  WITH CHECK (true);

-- ============================================================
-- sql/018_decision_logs.sql
-- ============================================================

-- 018_decision_logs.sql
-- TETO 1.6 可观测性：决策日志表
-- 存储每次关键判断的上下文，方便事后审计和诊断

CREATE TABLE IF NOT EXISTS decision_logs (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  decision_id TEXT NOT NULL,       -- 如在 id-registry.ts 中定义的决策 ID
  trace_id TEXT,                   -- 关联的 trace
  span_id TEXT,                    -- 关联的 span
  decision_type TEXT NOT NULL,     -- 'item_match' | 'field_write' | 'confidence_check' | 'type_infer' | ...
  input_summary TEXT,              -- 判断输入摘要（JSON 或文本）
  output_summary TEXT,             -- 判断输出摘要
  confidence REAL,                 -- 0.0 ~ 1.0
  rule_ids TEXT[] DEFAULT '{}',    -- 触发的规则 ID 列表
  error_code TEXT,                 -- 如果决策出错
  metadata JSONB DEFAULT '{}',     -- 额外上下文
  created_at TIMESTAMPTZ DEFAULT now()
);

-- 索引
CREATE INDEX IF NOT EXISTS idx_decision_logs_decision_id ON decision_logs(decision_id);
CREATE INDEX IF NOT EXISTS idx_decision_logs_trace_id ON decision_logs(trace_id);
CREATE INDEX IF NOT EXISTS idx_decision_logs_span_id ON decision_logs(span_id);
CREATE INDEX IF NOT EXISTS idx_decision_logs_decision_type ON decision_logs(decision_type);
CREATE INDEX IF NOT EXISTS idx_decision_logs_created_at ON decision_logs(created_at);

-- RLS
ALTER TABLE decision_logs ENABLE ROW LEVEL SECURITY;

-- 通过 service_role 允许系统写入
CREATE POLICY "Service can manage all decision logs"
  ON decision_logs FOR ALL
  USING (true)
  WITH CHECK (true);

-- ============================================================
-- sql/019_feature_flags.sql
-- ============================================================

-- 019_feature_flags.sql
-- TETO 1.6 功能开关机制
-- 仅服务端 service_role 可读，客户端不可直接访问

CREATE TABLE IF NOT EXISTS feature_flags (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  flag_name TEXT NOT NULL UNIQUE,
  enabled BOOLEAN NOT NULL DEFAULT false,
  description TEXT,
  rollout_percentage INTEGER NOT NULL DEFAULT 0 CHECK (rollout_percentage >= 0 AND rollout_percentage <= 100),
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- 1.6 首批开关
INSERT INTO feature_flags (flag_name, enabled, description, rollout_percentage) VALUES
  ('new_parse_engine', false, 'TETO 1.6 新版解析引擎', 0),
  ('debug_trace_page', false, '调试 Trace 页面', 0),
  ('computation_v2', false, 'TETO 1.6 新版计算引擎', 0)
ON CONFLICT (flag_name) DO NOTHING;

-- RLS：客户端不可直接访问
ALTER TABLE feature_flags ENABLE ROW LEVEL SECURITY;

-- 只有 service_role 可读
CREATE POLICY "Service role can read feature flags"
  ON feature_flags FOR SELECT
  USING (true);

-- 只有 service_role 可更新
CREATE POLICY "Service role can update feature flags"
  ON feature_flags FOR UPDATE
  USING (true)
  WITH CHECK (true);

CREATE POLICY "Service role can insert feature flags"
  ON feature_flags FOR INSERT
  WITH CHECK (true);

-- ============================================================
-- sql/020_input_id.sql
-- ============================================================

-- TETO 1.6: input_id 体系
-- 每次用户输入生成唯一 input_id，复合句拆分后的子句继承父 input_id
-- 子句另有独立的 child input_id（parent_input_id + "-{index}"）

-- 1. records 表新增 input_id（用户输入编号）
ALTER TABLE records ADD COLUMN IF NOT EXISTS input_id TEXT NULL;
CREATE INDEX idx_records_input_id ON records(input_id) WHERE input_id IS NOT NULL;

-- 2. records 表新增 parent_input_id（复合句父输入编号，子句指向父句）
ALTER TABLE records ADD COLUMN IF NOT EXISTS parent_input_id TEXT NULL;
CREATE INDEX idx_records_parent_input_id ON records(parent_input_id) WHERE parent_input_id IS NOT NULL;

-- 3. decision_logs 表新增 input_id（关联到具体输入）
ALTER TABLE decision_logs ADD COLUMN IF NOT EXISTS input_id TEXT NULL;
CREATE INDEX idx_decision_logs_input_id ON decision_logs(input_id) WHERE input_id IS NOT NULL;

-- ============================================================
-- sql/021_corrections_input_id.sql
-- ============================================================

-- 021_corrections_input_id.sql
-- TETO 1.6 — corrections 表追加 input_id 列，使纠错可追溯至原始输入

ALTER TABLE corrections ADD COLUMN IF NOT EXISTS input_id TEXT NULL;

CREATE INDEX IF NOT EXISTS idx_corrections_input_id ON corrections(input_id);

COMMENT ON COLUMN corrections.input_id IS '关联的 input_id（用户原始输入编号），用于错误趋势分析';

-- ============================================================
-- sql/022_corrections_rule_id.sql
-- ============================================================

-- 022_corrections_rule_id.sql
-- TETO 1.6 — corrections 表追加 rule_id 和 decision_type 列
-- 使纠错可追溯到出错的规则和决策类型，支持错误聚类

ALTER TABLE corrections ADD COLUMN IF NOT EXISTS rule_id TEXT NULL;
ALTER TABLE corrections ADD COLUMN IF NOT EXISTS decision_type TEXT NULL;

COMMENT ON COLUMN corrections.rule_id IS '出错的规则 ID（如 R-CL-001），用于定位哪条规则导致错误';
COMMENT ON COLUMN corrections.decision_type IS '出错的决策类型（DEC-SPLIT/DEC-TYPE/DEC-ITEM/DEC-TIME/DEC-AMOUNT/DEC-ADMISSION），用于错误聚类';

CREATE INDEX IF NOT EXISTS idx_corrections_rule_id ON corrections(rule_id);
CREATE INDEX IF NOT EXISTS idx_corrections_decision_type ON corrections(decision_type);

-- ============================================================
-- sql/023_inputs.sql
-- ============================================================

-- 023_inputs.sql
-- TETO 1.6 — 输入层：保存用户原始一句话输入
-- 作为 records 表的"上游"，承载未确认/正在澄清的中间态。
-- 任何录入入口（QuickInput / RecordEditDrawer / HistoryImport / API）都先落到这里。
--
-- 设计原则：
-- 1. inputs 是输入态，可改、可丢、可重解析，不参与统计
-- 2. records 是正式态，由 IngestPipeline 从 inputs 晋升而来
-- 3. 一个 input 可拆出多个 input_units（见 024）
--
-- 幂等：可重复执行。

CREATE TABLE IF NOT EXISTS inputs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  raw_input TEXT NOT NULL,                                                       -- 用户原始输入文本
  source TEXT NOT NULL DEFAULT 'quick'
    CHECK (source IN ('quick','edit','import','api')),                           -- 输入入口
  status TEXT NOT NULL DEFAULT 'pending'
    CHECK (status IN (
      'pending',         -- 刚收到，待解析
      'clarifying',      -- 在澄清流程中
      'completed',       -- 已全部生成 records
      'partial',         -- 3 轮封顶但仍部分入库
      'failed',          -- 解析全部失败
      'cancelled'        -- 用户取消
    )),
  trace_id TEXT,                                                                 -- 关联的 trace
  batch_id TEXT,                                                                 -- CSV 批量导入归属
  total_units INTEGER NOT NULL DEFAULT 0,                                        -- 拆分出几个 unit
  promoted_record_count INTEGER NOT NULL DEFAULT 0,                              -- 已晋升 record 数
  metadata JSONB DEFAULT '{}'::jsonb,                                            -- 自由扩展（输入设备、CSV 行号等）
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_inputs_user_id ON inputs(user_id);
CREATE INDEX IF NOT EXISTS idx_inputs_status ON inputs(status);
CREATE INDEX IF NOT EXISTS idx_inputs_trace_id ON inputs(trace_id) WHERE trace_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_inputs_batch_id ON inputs(batch_id) WHERE batch_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_inputs_created_at ON inputs(created_at DESC);

-- updated_at 触发器
CREATE OR REPLACE FUNCTION fn_inputs_set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_inputs_updated_at ON inputs;
CREATE TRIGGER trg_inputs_updated_at
  BEFORE UPDATE ON inputs
  FOR EACH ROW EXECUTE FUNCTION fn_inputs_set_updated_at();

-- RLS：用户只能管理自己的 inputs
ALTER TABLE inputs ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS inputs_user_select ON inputs;
CREATE POLICY inputs_user_select ON inputs FOR SELECT
  USING (auth.uid() = user_id);

DROP POLICY IF EXISTS inputs_user_insert ON inputs;
CREATE POLICY inputs_user_insert ON inputs FOR INSERT
  WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS inputs_user_update ON inputs;
CREATE POLICY inputs_user_update ON inputs FOR UPDATE
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS inputs_user_delete ON inputs;
CREATE POLICY inputs_user_delete ON inputs FOR DELETE
  USING (auth.uid() = user_id);

COMMENT ON TABLE inputs IS 'TETO 1.6 输入层：用户原始输入的容器，可承载未确认/澄清中状态';
COMMENT ON COLUMN inputs.raw_input IS '用户原始一句话输入';
COMMENT ON COLUMN inputs.source IS '输入来源：quick=快速输入, edit=编辑抽屉, import=CSV 导入, api=外部接口';
COMMENT ON COLUMN inputs.status IS '生命周期：pending → clarifying → completed/partial/failed/cancelled';

-- ============================================================
-- sql/024_input_units.sql
-- ============================================================

-- 024_input_units.sql
-- TETO 1.6 — 输入单元：input 拆分后的单条候选记录
-- 每个 unit 对应将来的 1 条 record（或 null 如果 cancelled / failed）
-- 承载澄清流程的所有中间态（解析结果、待答问题、已答历史、轮次计数）

CREATE TABLE IF NOT EXISTS input_units (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  input_id UUID NOT NULL REFERENCES inputs(id) ON DELETE CASCADE,
  user_id UUID NOT NULL,                                                         -- 冗余，提升 RLS 性能
  unit_index INTEGER NOT NULL DEFAULT 0,                                         -- 在原 input 中的顺序
  unit_text TEXT,                                                                -- 该单元对应的子句文本

  parsed_semantic JSONB DEFAULT '{}'::jsonb,                                     -- AI 解析结果（ParsedSemantic 形态）
  classifier_decision JSONB DEFAULT '{}'::jsonb,                                 -- {confidence, route, missing_fields, ...}
  field_ownership JSONB DEFAULT '{}'::jsonb,                                     -- {field_name: 'user'|'ai'|'rule'|'default'|'inherited'}
  confidence_overall NUMERIC(4,3),                                               -- 整体置信度 0.000~1.000

  pending_question JSONB,                                                        -- 当前待答 {field, prompt, kind, options?}
  answered_questions JSONB NOT NULL DEFAULT '[]'::jsonb,                         -- 已答列表 [{field, answer, at}]
  clarify_round INTEGER NOT NULL DEFAULT 0,                                      -- 已澄清几轮（封顶 3）
  clarify_max INTEGER NOT NULL DEFAULT 3,                                        -- 配置上限

  status TEXT NOT NULL DEFAULT 'pending_clarify'
    CHECK (status IN (
      'pending_clarify',   -- 等用户回答澄清
      'ready',             -- 解析完毕、可入库（高置信路径直达此态）
      'promoted',          -- 已生成 record
      'partial',           -- 3 轮封顶后用户选择"先这样保存"
      'cancelled',         -- 用户取消
      'failed'             -- 解析失败
    )),

  promoted_record_id UUID REFERENCES records(id) ON DELETE SET NULL,             -- 晋升后的 record id
  trace_id TEXT,

  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT input_units_clarify_round_max CHECK (clarify_round >= 0 AND clarify_round <= clarify_max + 1)
);

CREATE INDEX IF NOT EXISTS idx_input_units_input_id ON input_units(input_id);
CREATE INDEX IF NOT EXISTS idx_input_units_user_id ON input_units(user_id);
CREATE INDEX IF NOT EXISTS idx_input_units_status ON input_units(status);
CREATE INDEX IF NOT EXISTS idx_input_units_promoted_record_id
  ON input_units(promoted_record_id) WHERE promoted_record_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_input_units_trace_id
  ON input_units(trace_id) WHERE trace_id IS NOT NULL;

-- updated_at 触发器
CREATE OR REPLACE FUNCTION fn_input_units_set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_input_units_updated_at ON input_units;
CREATE TRIGGER trg_input_units_updated_at
  BEFORE UPDATE ON input_units
  FOR EACH ROW EXECUTE FUNCTION fn_input_units_set_updated_at();

-- RLS
ALTER TABLE input_units ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS input_units_user_select ON input_units;
CREATE POLICY input_units_user_select ON input_units FOR SELECT
  USING (auth.uid() = user_id);

DROP POLICY IF EXISTS input_units_user_insert ON input_units;
CREATE POLICY input_units_user_insert ON input_units FOR INSERT
  WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS input_units_user_update ON input_units;
CREATE POLICY input_units_user_update ON input_units FOR UPDATE
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS input_units_user_delete ON input_units;
CREATE POLICY input_units_user_delete ON input_units FOR DELETE
  USING (auth.uid() = user_id);

COMMENT ON TABLE input_units IS 'TETO 1.6 输入单元：input 拆分后的候选记录，承载澄清流程中间态';
COMMENT ON COLUMN input_units.classifier_decision IS '路由决策 JSON：{confidence, route: "direct"|"clarify", missing_fields[], ...}';
COMMENT ON COLUMN input_units.field_ownership IS '字段归属表：每个字段标 user/ai/rule/default/inherited，给解释面板用';
COMMENT ON COLUMN input_units.pending_question IS '当前待用户回答的问题 JSON：{field, prompt, kind: "select"|"text"|"datetime"|"number", options?}';
COMMENT ON COLUMN input_units.status IS '单元生命周期：pending_clarify → ready → promoted | partial | cancelled | failed';

-- ============================================================
-- sql/025_schema_alignment.sql
-- ============================================================

-- 025_schema_alignment.sql
-- TETO 1.6 — TS 与 SQL 模型对齐修复
--
-- 涉及问题（仅事实，不猜）：
-- 1. corrections 表 016 建表时缺 user_id 列，但应用层已在按 user_id 查/写
-- 2. records.review_status CHECK 约束不含 'disputed'，但 src/types/teto.ts 定义了
-- 3. records.time_precision CHECK 约束不含 'inherited'，但 src/types/teto.ts 定义了
-- 4. records 缺少 input_unit_id 反向关联（024 之后才补）
-- 5. records 缺少 record_quality_tag 列（前端色条用）
--
-- 全部幂等。重复执行不会出错。

-- ============================================================
-- 1. corrections 表补 user_id 列
-- ============================================================

ALTER TABLE corrections ADD COLUMN IF NOT EXISTS user_id UUID;

-- 历史数据回填（从 records.user_id 取）
UPDATE corrections c
SET user_id = r.user_id
FROM records r
WHERE c.record_id = r.id AND c.user_id IS NULL;

-- 加非空约束（仅在已无 NULL 的情况下）
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM corrections WHERE user_id IS NULL) THEN
    ALTER TABLE corrections ALTER COLUMN user_id SET NOT NULL;
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_corrections_user_id ON corrections(user_id);

-- 收紧 RLS：直接按 user_id 过滤，比 016 的 record_id IN (SELECT ...) 更高效
DO $$
BEGIN
  -- 016 的旧 policy
  EXECUTE 'DROP POLICY IF EXISTS corrections_user_policy ON corrections';
  EXECUTE 'DROP POLICY IF EXISTS corrections_user_select ON corrections';
  EXECUTE 'DROP POLICY IF EXISTS corrections_user_insert ON corrections';
  EXECUTE 'DROP POLICY IF EXISTS corrections_user_update ON corrections';
  EXECUTE 'DROP POLICY IF EXISTS corrections_user_delete ON corrections';
END $$;

CREATE POLICY corrections_user_select ON corrections FOR SELECT
  USING (auth.uid() = user_id);
CREATE POLICY corrections_user_insert ON corrections FOR INSERT
  WITH CHECK (auth.uid() = user_id);
CREATE POLICY corrections_user_update ON corrections FOR UPDATE
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);
CREATE POLICY corrections_user_delete ON corrections FOR DELETE
  USING (auth.uid() = user_id);

-- ============================================================
-- 2. records.review_status CHECK 加入 'disputed'
-- ============================================================

DO $$
DECLARE
  c_name TEXT;
BEGIN
  FOR c_name IN
    SELECT con.conname
    FROM pg_constraint con
    JOIN pg_class rel ON rel.oid = con.conrelid
    JOIN pg_namespace nsp ON nsp.oid = rel.relnamespace
    WHERE rel.relname = 'records'
      AND nsp.nspname = 'public'
      AND con.contype = 'c'
      AND pg_get_constraintdef(con.oid) ILIKE '%review_status%'
  LOOP
    EXECUTE format('ALTER TABLE records DROP CONSTRAINT IF EXISTS %I', c_name);
  END LOOP;
END $$;

ALTER TABLE records ADD CONSTRAINT records_review_status_check
  CHECK (review_status IN ('unchecked','confirmed','corrected','disputed'));

-- ============================================================
-- 3. records.time_precision CHECK 加入 'inherited'
-- ============================================================

DO $$
DECLARE
  c_name TEXT;
BEGIN
  FOR c_name IN
    SELECT con.conname
    FROM pg_constraint con
    JOIN pg_class rel ON rel.oid = con.conrelid
    JOIN pg_namespace nsp ON nsp.oid = rel.relnamespace
    WHERE rel.relname = 'records'
      AND nsp.nspname = 'public'
      AND con.contype = 'c'
      AND pg_get_constraintdef(con.oid) ILIKE '%time_precision%'
  LOOP
    EXECUTE format('ALTER TABLE records DROP CONSTRAINT IF EXISTS %I', c_name);
  END LOOP;
END $$;

ALTER TABLE records ADD CONSTRAINT records_time_precision_check
  CHECK (time_precision IS NULL OR time_precision IN ('exact','approx','fuzzy','unknown','inherited'));

-- ============================================================
-- 4. records 关联 input_units（反向追溯：record → 来自哪个 unit）
-- ============================================================

ALTER TABLE records ADD COLUMN IF NOT EXISTS input_unit_id UUID;

-- 仅在 input_units 表已存在的情况下加外键
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.tables
    WHERE table_schema = 'public' AND table_name = 'input_units'
  ) AND NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'records_input_unit_id_fkey'
  ) THEN
    ALTER TABLE records ADD CONSTRAINT records_input_unit_id_fkey
      FOREIGN KEY (input_unit_id) REFERENCES input_units(id) ON DELETE SET NULL;
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_records_input_unit_id
  ON records(input_unit_id) WHERE input_unit_id IS NOT NULL;

COMMENT ON COLUMN records.input_unit_id IS '反向追溯：本 record 来自哪个 input_unit（024 表）';

-- ============================================================
-- 5. records 加 record_quality_tag（前端色条用）
-- ============================================================

ALTER TABLE records ADD COLUMN IF NOT EXISTS record_quality_tag TEXT;

DO $$
DECLARE
  c_name TEXT;
BEGIN
  FOR c_name IN
    SELECT con.conname
    FROM pg_constraint con
    JOIN pg_class rel ON rel.oid = con.conrelid
    JOIN pg_namespace nsp ON nsp.oid = rel.relnamespace
    WHERE rel.relname = 'records'
      AND nsp.nspname = 'public'
      AND con.contype = 'c'
      AND pg_get_constraintdef(con.oid) ILIKE '%record_quality_tag%'
  LOOP
    EXECUTE format('ALTER TABLE records DROP CONSTRAINT IF EXISTS %I', c_name);
  END LOOP;
END $$;

ALTER TABLE records ADD CONSTRAINT records_record_quality_tag_check
  CHECK (record_quality_tag IS NULL OR record_quality_tag IN (
    'ai_high',     -- 全 AI 解析、整体置信度高
    'clarified',   -- 用户在录入时澄清过至少一个字段
    'corrected',   -- 用户事后修正过
    'ai_failed',   -- AI 解析失败强写默认值
    'partial'      -- 3 轮封顶后仍缺关键字段
  ));

CREATE INDEX IF NOT EXISTS idx_records_record_quality_tag
  ON records(record_quality_tag) WHERE record_quality_tag IS NOT NULL;

COMMENT ON COLUMN records.record_quality_tag IS '记录质量标签（前端色条）：ai_high / clarified / corrected / ai_failed / partial';

-- ============================================================
-- sql/026_errors.sql
-- ============================================================

-- 026_errors.sql
-- TETO 1.6 — 客户端 + 服务端运行时错误聚合表
-- 让前端 console.error / fetch 失败 / 组件崩溃都不再丢失，可追溯。

CREATE TABLE IF NOT EXISTS errors (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID,                                                                  -- 可空（未登录或匿名场景）
  error_code TEXT NOT NULL,                                                      -- 'AI_PARSE_FAILED'/'CLIENT_FETCH_ERROR'/...
  message TEXT NOT NULL,                                                         -- 简明错误描述
  stack TEXT,                                                                    -- 堆栈
  source TEXT NOT NULL DEFAULT 'server'
    CHECK (source IN ('server','client')),                                       -- 错误来源
  severity TEXT NOT NULL DEFAULT 'error'
    CHECK (severity IN ('warn','error','fatal')),
  trace_id TEXT,                                                                 -- 关联 trace
  record_id UUID,                                                                -- 关联 records（可空）
  input_id UUID,                                                                 -- 关联 inputs（可空）
  url TEXT,                                                                      -- 出错时的页面或接口路径
  user_agent TEXT,                                                               -- 客户端环境
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,                                   -- 自由扩展
  occurred_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_errors_user_id ON errors(user_id);
CREATE INDEX IF NOT EXISTS idx_errors_error_code ON errors(error_code);
CREATE INDEX IF NOT EXISTS idx_errors_occurred_at ON errors(occurred_at DESC);
CREATE INDEX IF NOT EXISTS idx_errors_severity ON errors(severity);
CREATE INDEX IF NOT EXISTS idx_errors_trace_id ON errors(trace_id) WHERE trace_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_errors_record_id ON errors(record_id) WHERE record_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_errors_input_id ON errors(input_id) WHERE input_id IS NOT NULL;

-- RLS
ALTER TABLE errors ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS errors_user_select ON errors;
CREATE POLICY errors_user_select ON errors FOR SELECT
  USING (auth.uid() = user_id OR user_id IS NULL);

DROP POLICY IF EXISTS errors_user_insert ON errors;
CREATE POLICY errors_user_insert ON errors FOR INSERT
  WITH CHECK (user_id IS NULL OR auth.uid() = user_id);

-- service_role 默认 bypass RLS，无需显式 policy

COMMENT ON TABLE errors IS 'TETO 1.6 错误聚合：所有运行时异常的统一记录';
COMMENT ON COLUMN errors.error_code IS '错误码（如 AI_PARSE_FAILED、CLIENT_FETCH_ERROR、CLIENT_BOUNDARY_CRASH）';
COMMENT ON COLUMN errors.source IS '来源：server=服务端, client=浏览器';
COMMENT ON COLUMN errors.severity IS '严重度：warn/error/fatal';

-- ============================================================
-- sql/027_record_categories.sql
-- ============================================================

-- TETO 1.7: 记录分类字段（大类 / 子类）
-- 请在 Supabase SQL Editor 中执行

ALTER TABLE records
  ADD COLUMN IF NOT EXISTS category TEXT,
  ADD COLUMN IF NOT EXISTS subcategory TEXT;

CREATE INDEX IF NOT EXISTS idx_records_category
  ON records(user_id, category)
  WHERE category IS NOT NULL;

-- ============================================================
-- sql/028_todos.sql
-- ============================================================

-- TETO 1.7: 待办表
-- 请在 Supabase SQL Editor 中执行

CREATE TABLE IF NOT EXISTS todos (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  content TEXT NOT NULL,
  category VARCHAR(50),
  subcategory VARCHAR(50),
  item_id UUID REFERENCES items(id) ON DELETE SET NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'pending',
  record_id UUID REFERENCES records(id) ON DELETE SET NULL,
  sort_order INT NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT todos_status_check CHECK (status IN ('pending', 'in_progress', 'completed'))
);

CREATE INDEX IF NOT EXISTS idx_todos_user_id ON todos(user_id);
CREATE INDEX IF NOT EXISTS idx_todos_status ON todos(user_id, status);
CREATE INDEX IF NOT EXISTS idx_todos_item_id ON todos(user_id, item_id) WHERE item_id IS NOT NULL;

ALTER TABLE todos ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS todos_user_isolation ON todos;
CREATE POLICY todos_user_isolation ON todos
  FOR ALL
  USING (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid());

-- ============================================================
-- sql/029_recurring_activities.sql
-- ============================================================

-- TETO 1.7: 常用事项（重复活动模板）
-- 请在 Supabase SQL Editor 中执行

CREATE TABLE IF NOT EXISTS recurring_activities (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  name VARCHAR(200) NOT NULL,
  category VARCHAR(50),
  subcategory VARCHAR(50),
  item_id UUID REFERENCES items(id) ON DELETE SET NULL,
  sort_order INT NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_recurring_activities_user_id ON recurring_activities(user_id);

ALTER TABLE recurring_activities ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS recurring_user_isolation ON recurring_activities;
CREATE POLICY recurring_user_isolation ON recurring_activities
  FOR ALL
  USING (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid());

-- ============================================================
-- sql/030_project_notes.sql
-- ============================================================

-- TETO 1.7: 项目笔记
-- 请在 Supabase SQL Editor 中执行

CREATE TABLE IF NOT EXISTS project_notes (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  item_id UUID NOT NULL REFERENCES items(id) ON DELETE CASCADE,
  content TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_project_notes_item_id ON project_notes(user_id, item_id);

ALTER TABLE project_notes ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS project_notes_user_isolation ON project_notes;
CREATE POLICY project_notes_user_isolation ON project_notes
  FOR ALL
  USING (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid());

-- ============================================================
-- sql/031_items_parent.sql
-- ============================================================

-- TETO 1.7: items 表加 parent_item_id，支持大类→事项层级
-- 大类 = parent_item_id IS NULL 的顶层 item
-- 事项 = parent_item_id 指向顶层 item 的子 item

ALTER TABLE items
  ADD COLUMN IF NOT EXISTS parent_item_id UUID REFERENCES items(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS items_parent_item_id_idx ON items(parent_item_id);

-- ============================================================
-- sql/032_records_tool_label.sql
-- ============================================================

-- 记录层「工具/载体」字段（如：不背单词、多邻国）
ALTER TABLE records ADD COLUMN IF NOT EXISTS tool_label text;

COMMENT ON COLUMN records.tool_label IS '工具/载体标签，与子项正交，如 app 名或自学';

-- ============================================================
-- sql/033_user_tools.sql
-- ============================================================

-- 用户自定义「工具/载体」选项（记录仍用 records.tool_label 存选中项名称）
CREATE TABLE IF NOT EXISTS user_tools (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  title text NOT NULL,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (user_id, title)
);

CREATE INDEX IF NOT EXISTS idx_user_tools_user_id ON user_tools(user_id, sort_order);

ALTER TABLE user_tools ENABLE ROW LEVEL SECURITY;

CREATE POLICY user_tools_select ON user_tools
  FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY user_tools_insert ON user_tools
  FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY user_tools_update ON user_tools
  FOR UPDATE USING (auth.uid() = user_id);

CREATE POLICY user_tools_delete ON user_tools
  FOR DELETE USING (auth.uid() = user_id);

COMMENT ON TABLE user_tools IS '用户自定义工具/载体选项，供录入时选择';

-- ============================================================
-- sql/034_activity_sessions_events.sql
-- ============================================================

-- TETO 1.8: 活动会话 + 事件流
-- 请在 Supabase SQL Editor 中执行

-- 会话字段（复用 records 表作为会话容器）
ALTER TABLE records
  ADD COLUMN IF NOT EXISTS paused_total_seconds INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS paused_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS parent_session_id UUID REFERENCES records(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS session_state TEXT NOT NULL DEFAULT 'running'
    CHECK (session_state IN ('running', 'paused', 'nested_paused'));

CREATE INDEX IF NOT EXISTS idx_records_parent_session ON records(user_id, parent_session_id)
  WHERE parent_session_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_records_session_state ON records(user_id, session_state)
  WHERE lifecycle_status = 'active';

-- 活动事件流
CREATE TABLE IF NOT EXISTS activity_events (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  session_id UUID NOT NULL REFERENCES records(id) ON DELETE CASCADE,
  event_type TEXT NOT NULL CHECK (event_type IN (
    'progress', 'idea', 'plan', 'milestone',
    'ai_user', 'ai_reply',
    'pause', 'resume', 'sub_start', 'sub_end',
    'structured'
  )),
  content TEXT NOT NULL DEFAULT '',
  payload JSONB NOT NULL DEFAULT '{}'::jsonb,
  occurred_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_activity_events_session ON activity_events(user_id, session_id, occurred_at);
CREATE INDEX IF NOT EXISTS idx_activity_events_type ON activity_events(user_id, event_type, occurred_at DESC);

ALTER TABLE activity_events ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS activity_events_user_isolation ON activity_events;
CREATE POLICY activity_events_user_isolation ON activity_events
  FOR ALL
  USING (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid());

-- Item 默认职能/工具预设
ALTER TABLE items
  ADD COLUMN IF NOT EXISTS default_function_tag_id UUID REFERENCES tags(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS default_tool_label TEXT;

-- UserRule 扩展：metadata 存职能 tag_id / tool_label
ALTER TABLE user_rules
  ADD COLUMN IF NOT EXISTS metadata JSONB NOT NULL DEFAULT '{}'::jsonb;

-- 扩展 rule_type 约束（含 function_mapping / tool_mapping）
ALTER TABLE user_rules DROP CONSTRAINT IF EXISTS user_rules_rule_type_check;
ALTER TABLE user_rules ADD CONSTRAINT user_rules_rule_type_check
  CHECK (rule_type IN (
    'item_mapping', 'sub_item_mapping', 'type_routing', 'fuzzy_resolution',
    'function_mapping', 'tool_mapping'
  ));

-- 项目笔记增强
ALTER TABLE project_notes
  ADD COLUMN IF NOT EXISTS note_type TEXT NOT NULL DEFAULT 'knowledge'
    CHECK (note_type IN ('knowledge', 'review', 'insight', 'reflection', 'milestone')),
  ADD COLUMN IF NOT EXISTS source_event_id UUID REFERENCES activity_events(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS record_id UUID REFERENCES records(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_project_notes_type ON project_notes(user_id, note_type);

-- 用户画像（滚动派生）
CREATE TABLE IF NOT EXISTS user_profiles (
  user_id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  active_hours JSONB NOT NULL DEFAULT '[]'::jsonb,
  avg_focus_minutes NUMERIC,
  top_items JSONB NOT NULL DEFAULT '[]'::jsonb,
  interrupt_patterns JSONB NOT NULL DEFAULT '[]'::jsonb,
  mood_summary JSONB NOT NULL DEFAULT '{}'::jsonb,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE user_profiles ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS user_profiles_user_isolation ON user_profiles;
CREATE POLICY user_profiles_user_isolation ON user_profiles
  FOR ALL
  USING (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid());

-- ============================================================
-- sql/035_records_related_objects.sql
-- ============================================================

-- 035_records_related_objects.sql
-- 为记录增加「涉及对象」字段，用于存储弱关联的公司名、人名、客户名等对象线索
-- 这些对象先于事项存在，可以在持续跟进后升级为正式事项

ALTER TABLE records ADD COLUMN IF NOT EXISTS related_objects text[] DEFAULT '{}';

-- 同时为 review_status 增加枚举说明（不修改约束，保留文档性注释）
-- 'unchecked': 新创建，AI 建议未确认
-- 'confirmed': 用户或高置信自动确认
-- 'corrected': 用户纠正了 AI 建议
-- 'disputed': 用户标记为不确定

COMMENT ON COLUMN records.related_objects IS
  '弱关联对象线索，存储记录中提到但未升级为正式 item 的公司名、人名、客户名等';

-- ============================================================
-- sql/036_user_rules_extend.sql
-- ============================================================

-- ============================================================
-- 036: 扩展 user_rules 表的规则类型与来源枚举
--
-- 新增：
--   rule_type: no_assign — 「不归类」标记，避免同类词反复被猜
--   source: user_confirm — 用户手动确认/否定后写入
--   source: preset       — 系统内置词典种子
-- ============================================================

-- 移除旧的 rule_type CHECK 约束，改为更宽松版本
ALTER TABLE user_rules
  DROP CONSTRAINT IF EXISTS user_rules_rule_type_check;

ALTER TABLE user_rules
  ADD CONSTRAINT user_rules_rule_type_check
  CHECK (rule_type IN (
    'item_mapping', 'sub_item_mapping', 'type_routing',
    'fuzzy_resolution', 'function_mapping', 'tool_mapping',
    'no_assign'
  ));

-- ============================================================
-- sql/037_records_display_no.sql
-- ============================================================

-- 记录展示编号：YYYYMMDD + 4 位当日序号（如 202601020001）
ALTER TABLE records ADD COLUMN IF NOT EXISTS display_no TEXT NULL;

CREATE INDEX IF NOT EXISTS idx_records_user_display_no
  ON records(user_id, display_no)
  WHERE display_no IS NOT NULL;

COMMENT ON COLUMN records.display_no IS '用户可见记录编号，创建时按归属日分配';

-- ============================================================
-- sql/038_record_notes_array.sql
-- ============================================================

-- 多条笔记：JSON 数组
ALTER TABLE records
  ADD COLUMN IF NOT EXISTS notes JSONB NOT NULL DEFAULT '[]'::jsonb;

-- 回填旧随手记：原文进 raw_input，清空 content
UPDATE records
SET raw_input = content, content = ''
WHERE input_source = 'quick'
  AND (raw_input IS NULL OR trim(raw_input) = '')
  AND content IS NOT NULL
  AND trim(content) <> '';

UPDATE records
SET notes = jsonb_build_array(note)
WHERE (notes IS NULL OR notes = '[]'::jsonb)
  AND note IS NOT NULL
  AND trim(note) <> '';

-- ============================================================
-- sql/039_function_tag_scope.sql
-- ============================================================

-- 动作标签可归属于一个一类事项；NULL 表示兼容历史的全局动作标签。
ALTER TABLE public.tags
  ADD COLUMN IF NOT EXISTS scope_item_id UUID REFERENCES public.items(id) ON DELETE CASCADE;

CREATE INDEX IF NOT EXISTS idx_tags_user_function_scope
  ON public.tags(user_id, type, scope_item_id);

COMMENT ON COLUMN public.tags.scope_item_id IS
  '动作标签所属的一类事项。NULL 为历史全局标签，非空时仅在该一类事项范围内可见和自动匹配。';

-- ============================================================
-- sql/040_finance_accounts.sql
-- ============================================================

-- 财务账户主数据 + records 关联字段
-- Phase 1: 账户实体化
-- Phase 3: 转账字段

CREATE TABLE IF NOT EXISTS finance_accounts (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  name text NOT NULL,
  account_type text NOT NULL CHECK (
    account_type IN ('wechat', 'alipay', 'bank_card', 'cash', 'credit_card', 'other')
  ),
  icon text,
  opening_balance numeric(12,2) NOT NULL DEFAULT 0,
  currency text NOT NULL DEFAULT 'CNY',
  is_archived boolean NOT NULL DEFAULT false,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (user_id, name)
);

CREATE INDEX IF NOT EXISTS idx_finance_accounts_user_id
  ON finance_accounts(user_id, sort_order);

ALTER TABLE finance_accounts ENABLE ROW LEVEL SECURITY;

CREATE POLICY finance_accounts_select ON finance_accounts
  FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY finance_accounts_insert ON finance_accounts
  FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY finance_accounts_update ON finance_accounts
  FOR UPDATE USING (auth.uid() = user_id);

CREATE POLICY finance_accounts_delete ON finance_accounts
  FOR DELETE USING (auth.uid() = user_id);

COMMENT ON TABLE finance_accounts IS '用户财务账户：微信/支付宝/银行卡等';

-- records 关联财务账户
ALTER TABLE records ADD COLUMN IF NOT EXISTS finance_account_id uuid
  REFERENCES finance_accounts(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_records_finance_account_id
  ON records(finance_account_id) WHERE finance_account_id IS NOT NULL;

COMMENT ON COLUMN records.finance_account_id IS '收支归属账户；优先于 tool_label 用于财务聚合';

-- Phase 3: 转账目标账户
ALTER TABLE records ADD COLUMN IF NOT EXISTS transfer_to_account_id uuid
  REFERENCES finance_accounts(id) ON DELETE SET NULL;

COMMENT ON COLUMN records.transfer_to_account_id IS '转账转入账户；仅 money_direction=transfer 时使用';

-- 扩展 money_direction 支持 transfer
ALTER TABLE records DROP CONSTRAINT IF EXISTS records_money_direction_check;
ALTER TABLE records ADD CONSTRAINT records_money_direction_check
  CHECK (money_direction IS NULL OR money_direction IN ('expense', 'income', 'none', 'transfer'));
