-- Bootstrap 004: RPC functions
-- Generated by scripts/build-bootstrap-sql.mjs — do not edit by hand

-- ============================================================
-- sql/rpc/rpc_delete_item.sql
-- ============================================================

-- P5: deleteItem 事务化 RPC
-- 将关联记录/目标/阶段置空，删除子项，软删除事项 — 原子操作
-- 部署：在 Supabase Dashboard SQL Editor 中手动执行

CREATE OR REPLACE FUNCTION rpc_delete_item(
  p_user_id UUID,
  p_item_id UUID
)
RETURNS JSONB
LANGUAGE plpgsql
AS $$
DECLARE
  v_sub_item_count INT;
  v_record_count INT;
  v_goal_count INT;
  v_phase_count INT;
BEGIN
  -- Step 1: 验证 item 归属
  IF NOT EXISTS (SELECT 1 FROM items WHERE id = p_item_id AND user_id = p_user_id) THEN
    RETURN jsonb_build_object('ok', false, 'error', 'ITEM_NOT_FOUND');
  END IF;

  -- Step 2: 置空关联记录的 item_id/phase_id/sub_item_id
  UPDATE records SET item_id = NULL, phase_id = NULL, sub_item_id = NULL
    WHERE item_id = p_item_id AND user_id = p_user_id;

  -- Step 3: 置空关联目标的 item_id/sub_item_id
  UPDATE goals SET item_id = NULL, sub_item_id = NULL
    WHERE item_id = p_item_id AND user_id = p_user_id;

  -- Step 4: 置空关联阶段的 item_id
  UPDATE phases SET item_id = NULL
    WHERE item_id = p_item_id AND user_id = p_user_id;

  -- Step 5: 物理删除子事项（record_links CASCADE）
  DELETE FROM sub_items WHERE item_id = p_item_id AND user_id = p_user_id;

  -- Step 6: 软删除事项
  UPDATE items SET status = '已搁置' WHERE id = p_item_id AND user_id = p_user_id;

  RETURN jsonb_build_object('ok', true);
EXCEPTION WHEN OTHERS THEN
  RETURN jsonb_build_object('ok', false, 'error', SQLERRM);
END;
$$;

-- ============================================================
-- sql/rpc/rpc_delete_phase.sql
-- ============================================================

-- P5: deletePhase 事务化 RPC
-- 置空关联记录/目标的 phase_id，物理删除阶段 — 原子操作
-- 部署：在 Supabase Dashboard SQL Editor 中手动执行

CREATE OR REPLACE FUNCTION rpc_delete_phase(
  p_user_id UUID,
  p_phase_id UUID
)
RETURNS JSONB
LANGUAGE plpgsql
AS $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM phases WHERE id = p_phase_id AND user_id = p_user_id) THEN
    RETURN jsonb_build_object('ok', false, 'error', 'PHASE_NOT_FOUND');
  END IF;

  UPDATE records SET phase_id = NULL WHERE phase_id = p_phase_id AND user_id = p_user_id;
  UPDATE goals SET phase_id = NULL WHERE phase_id = p_phase_id AND user_id = p_user_id;
  DELETE FROM phases WHERE id = p_phase_id AND user_id = p_user_id;

  RETURN jsonb_build_object('ok', true);
EXCEPTION WHEN OTHERS THEN
  RETURN jsonb_build_object('ok', false, 'error', SQLERRM);
END;
$$;

-- ============================================================
-- sql/rpc/rpc_delete_sub_item.sql
-- ============================================================

-- P5: deleteSubItem 事务化 RPC
-- 置空关联记录/目标的 sub_item_id，物理删除子项 — 原子操作
-- 部署：在 Supabase Dashboard SQL Editor 中手动执行

CREATE OR REPLACE FUNCTION rpc_delete_sub_item(
  p_user_id UUID,
  p_sub_item_id UUID
)
RETURNS JSONB
LANGUAGE plpgsql
AS $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM sub_items WHERE id = p_sub_item_id AND user_id = p_user_id) THEN
    RETURN jsonb_build_object('ok', false, 'error', 'SUB_ITEM_NOT_FOUND');
  END IF;

  UPDATE records SET sub_item_id = NULL WHERE sub_item_id = p_sub_item_id AND user_id = p_user_id;
  UPDATE goals SET sub_item_id = NULL WHERE sub_item_id = p_sub_item_id AND user_id = p_user_id;
  DELETE FROM sub_items WHERE id = p_sub_item_id AND user_id = p_user_id;

  RETURN jsonb_build_object('ok', true);
EXCEPTION WHEN OTHERS THEN
  RETURN jsonb_build_object('ok', false, 'error', SQLERRM);
END;
$$;

-- ============================================================
-- sql/rpc/rpc_promote_sub_item.sql
-- ============================================================

-- P5: promoteSubItem 事务化 RPC
-- 子项升格为独立事项：创建新事项 → 迁移记录/目标 → 原子操作
-- 部署：在 Supabase Dashboard SQL Editor 中手动执行

CREATE OR REPLACE FUNCTION rpc_promote_sub_item(
  p_user_id UUID,
  p_sub_item_id UUID,
  p_new_title TEXT DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
AS $$
DECLARE
  v_sub_item RECORD;
  v_new_item_id UUID;
BEGIN
  SELECT * INTO v_sub_item FROM sub_items WHERE id = p_sub_item_id AND user_id = p_user_id;
  IF NOT FOUND THEN
    RETURN jsonb_build_object('ok', false, 'error', 'SUB_ITEM_NOT_FOUND');
  END IF;

  -- 创建新 item
  INSERT INTO items (user_id, title, status, description)
  VALUES (p_user_id, COALESCE(p_new_title, v_sub_item.title), '活跃', v_sub_item.description)
  RETURNING id INTO v_new_item_id;

  -- 迁移 records
  UPDATE records SET item_id = v_new_item_id, sub_item_id = NULL
    WHERE sub_item_id = p_sub_item_id AND user_id = p_user_id;

  -- 迁移 goals
  UPDATE goals SET item_id = v_new_item_id, sub_item_id = NULL
    WHERE sub_item_id = p_sub_item_id AND user_id = p_user_id;

  RETURN jsonb_build_object('ok', true, 'new_item_id', v_new_item_id);
EXCEPTION WHEN OTHERS THEN
  RETURN jsonb_build_object('ok', false, 'error', SQLERRM);
END;
$$;
